try {
window.gdprUser=true;
} catch (e) {
console.error(e);
}
try {
(function(a){a=a.tmntag=a.tmntag||{};a._config={};a._config.GDPR_PII_CMP_LOAD_BOOST_DOMAINS=[];a._config.GDPR_MINISTUB_FOR_NON_EU_USERS_DOMAIN_LIST=[];a._config.GDPR_QUANTCAST_CONFIGURATION={};var b={Language:"en","Initial Screen Reject Button Text":"I do not accept","Initial Screen Accept Button Text":"I accept","Purpose Screen Body Text":"You can set your consent preferences and determine how you want your data to be used based on the purposes below. You may set your preferences for us independently from those of third-party partners. Each purpose has a description so that you know how we and partners use your data.",
"Vendor Screen Body Text":"You can set consent preferences for each individual third-party company below. Expand each company list item to see what purposes they use data for to help make your choices. In some cases, companies may disclose that they use your data without asking for your consent, based on their legitimate interests. You can click on their privacy policies for more information and to opt out.","Vendor Screen Accept All Button Text":"Accept all","Vendor Screen Reject All Button Text":"Reject all",
"Initial Screen Body Text":"We and our partners use technology such as cookies on our site to personalise content and ads, provide social media features, and analyse our traffic. Click below to consent to the use of this technology across the web. You can change your mind and change your consent choices at anytime by returning to this site.","Initial Screen Body Text Option":1,"Consent Scope":"service","No Option":false};a._config.GDPR_QUANTCAST_CONFIGURATION["newsarama.com"]=Object.assign({},b,{distribution:[{mode:"quantcast",
experiment:160,ratio:1},{mode:"purch",experiment:161,ratio:1}],"Publisher Name":"Newsarama","Publisher Logo":"https://dg876rejmw3ebkm51boa0sx2-wpengine.netdna-ssl.com/wp-content/uploads/2018/08/newsarama-logo.png"});a._config.GDPR_QUANTCAST_CONFIGURATION["laptopmag.com"]=Object.assign({},b,{distribution:[{mode:"quantcast",experiment:160,ratio:1},{mode:"purch",experiment:161,ratio:1}],"Publisher Name":"Laptop","Publisher Logo":"https://dg876rejmw3ebkm51boa0sx2-wpengine.netdna-ssl.com/wp-content/uploads/2018/08/laptopmag-logo.png"});
a._config.GDPR_QUANTCAST_CONFIGURATION["cyclingnews.com"]=Object.assign({},b,{distribution:[{mode:"quantcast",ratio:1}],"Publisher Name":"Cycling News","Publisher Logo":"https://dg876rejmw3ebkm51boa0sx2-wpengine.netdna-ssl.com/wp-content/uploads/2019/03/Cycling-news.png"})})(window);
} catch (e) {
console.error(e);
}
!function(f,g){for(var a in g)f[a]=g[a]}(window,function(f){function g(b){if(a[b])return a[b].exports;var d=a[b]={i:b,l:!1,exports:{}};return f[b].call(d.exports,d,d.exports,g),d.l=!0,d.exports}var a={};return g.m=f,g.c=a,g.d=function(a,d,t){g.o(a,d)||Object.defineProperty(a,d,{enumerable:!0,get:t})},g.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(a,"__esModule",{value:!0})},g.t=function(a,d){if(1&d&&
(a=g(a)),8&d)return a;if(4&d&&"object"==typeof a&&a&&a.__esModule)return a;var b=Object.create(null);if(g.r(b),Object.defineProperty(b,"default",{enumerable:!0,value:a}),2&d&&"string"!=typeof a)for(var q in a)g.d(b,q,function(b){return a[b]}.bind(null,q));return b},g.n=function(a){var b=a&&a.__esModule?function(){return a.default}:function(){return a};return g.d(b,"a",b),b},g.o=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)},g.p="",g(g.s=28)}([function(f,g,a){function b(a){return window.tmntag.markupsInfo&&
window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].rtbSold}function d(a){return window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].bidderid}function t(a){if(window.tmntag_getAdunitFromCache)return(a=window.tmntag_getAdunitFromCache(a))&&a.dfpCampaignId;return null}function q(a){if(window.tmntag_getAdunitFromCache)return(a=window.tmntag_getAdunitFromCache(a))&&a.dfpLineItemId;return null}function m(a,c){window.tmntag.refresh&&window.tmntag.refresh(a,void 0,
String(c.refreshCount-1))}function r(a,c){return!!window.tmntag&&(void 0===a?window.tmntag.adparams:void 0===c?window.tmntag.adparams&&window.tmntag.adparams[a]:window.tmntag.adparams&&window.tmntag.adparams[a]&&window.tmntag.adparams[a][c])}function l(){var a,c=!1;return a=navigator.userAgent||navigator.vendor||window.opera,(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||
/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4)))&&(c=!0),c}a.d(g,"a",function(){return b}),a.d(g,"d",function(){return d}),a.d(g,"f",function(){return t}),a.d(g,"e",function(){return q}),a.d(g,"c",function(){return m}),a.d(g,"g",function(){return r}),a.d(g,"b",function(){return p}),a.d(g,"h",function(){return l});var p=function(a,c,e){var b=2<arguments.length&&void 0!==e?e:{};return a.reduce(function(a,e){return-1!==c.indexOf(e[0])&&(a[e[0]]=e[1]),a},b)}},function(f,g){f.exports=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");
}},function(f,g){function a(a,d){for(var b=0;b<d.length;b++){var q=d[b];q.enumerable=q.enumerable||!1,q.configurable=!0,"value"in q&&(q.writable=!0),Object.defineProperty(a,q.key,q)}}f.exports=function(b,d,f){return d&&a(b.prototype,d),f&&a(b,f),b}},function(f,g,a){a.d(g,"d",function(){return m}),a.d(g,"c",function(){return r}),a.d(g,"e",function(){return l}),a.d(g,"b",function(){return c}),a.d(g,"a",function(){return e});var b=a(5),d=a(4),t=a(9),q="allowed",m=function(a){q=a},r=function(){return q},
l=function(a){return new Promise(function(c){!function z(){"function"==typeof window.__cmp?("function"==typeof a&&a(),c()):window.setTimeout(z,100)}()})},p=function(){for(var a=arguments.length,c=new Array(a),e=0;e<a;e++)c[e]=arguments[e];return new Promise(function(a){var e;(e=window).__cmp.apply(e,c.concat([function(c){a(c)}]))})},n=function(a){return function(){return p("getVendorConsents",a?[a]:[])}},c=function(){return function(){return p("getConsentData",null)}},e=function(a,c){if(Object(t.d)())l().then(n(a)).then(function(e){var b=
e.gdprApplies;e=e.vendorConsents;return b?e&&e[a]?c():null:c()});else switch(q){case "blocked":return null;case "allowed":return c();case "managed":var e=Object(d.a)("guitarworld.com|loudersound.com|phonandroid.com|frandroid.com|generation-nt.com|gamergen.com|numerama.com|driverscloud.com|hitek.fr|tomsguide.fr|tomshardware.fr|creativebloq.com|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com");if(Object(b.a)(e))return c();l().then(function(a){return function(){return p("addEventListener",a)}}("cmpReady")).then(n(a)).then(function(e){return(e=e.vendorConsents)&&e[a]?c():null});break;default:return c()}return null}},function(f,g,a){a.d(g,"a",function(){return b});var b=function(a){return a&&
0!==a.indexOf("$")?a.split("|"):[]}},function(f,g,a){function b(){return Boolean((0<arguments.length&&void 0!==arguments[0]?arguments[0]:[]).find(function(a){return-1!==document.location.hostname.indexOf(a)}))}a.d(g,"a",function(){return b})},,function(f,g,a){function b(a){var c=a.getBoundingClientRect();a=c.top;var e=c.right,b=c.bottom,A=c.left,m=.5*c.width,c=.5*c.height;return c<b&&window.innerWidth-A>m&&window.innerHeight-a>c&&m<e}f=a(1);var d=a.n(f);f=a(2);var t=a.n(f),q=function(){function a(c){d()(this,
a),this.elements=c,this.current=[],this.handlers={enter:[],exit:[]}}return t()(a,[{key:"check",value:function(){var a=this;return this.elements.forEach(function(c){var e=b(c),m=a.current.indexOf(c),A=-1<m,n=!e&&A;e&&!A&&(a.current.push(c),a.emit("enter",c)),n&&(a.current.splice(m,1),a.emit("exit",c))},this),this}},{key:"on",value:function(a,c){return this.handlers[a].push(c),this}},{key:"emit",value:function(a,c){for(var e=this.handlers[a].length;-1<--e;)this.handlers[a][e](c);return this}}]),a}(),
m,r,l,p,n,c,e,A,y={history:[]},E=(m=function(){y.history.forEach(function(a){y[a].check()})},r=100,c=null,e=0,A=function(){e=new Date,c=null,n=m.apply(l,p),c||(l=p=null)},function(){var a=new Date,b=r-(a-e);return l=this,p=arguments,b<=0||r<b?(c&&(clearTimeout(c),c=null),e=a,n=m.apply(l,p),c||(l=p=null)):c=c||setTimeout(A,b),n});["scroll","resize","load"].forEach(function(a){window.addEventListener(a,E)}),window.MutationObserver&&window.addEventListener("DOMContentLoaded",function(){(new MutationObserver(E)).observe(document.body,
{attributes:!0,childList:!0,subtree:!0})});a=function(a){if("string"!=typeof a)return null;var c=[].slice.call(document.querySelectorAll(a));return-1<y.history.indexOf(a)?y[a].elements=c:(y[a]=new q(c),y.history.push(a)),y[a]};a.is=b,g.a=a},function(f,g){function a(b){return(a="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a})(b)}function b(d){return"function"==
typeof Symbol&&"symbol"===a(Symbol.iterator)?f.exports=b=function(b){return a(b)}:f.exports=b=function(b){return b&&"function"==typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":a(b)},b(d)}f.exports=b},function(f,g,a){a.d(g,"b",function(){return r}),a.d(g,"d",function(){return p}),a.d(g,"c",function(){return n});f=a(23);var b=a.n(f),d=a(4),t=a(5),q=a(10),m=function(){var a=window.tmntag.config.get("GDPR_QUANTCAST_CONFIGURATION")||{},e=Object.keys(a).find(function(a){return-1!==
document.location.hostname.indexOf(a)});return e?a[e]:null};g.a=function(){function a(a){var c,e="string"==typeof a.data;if((c=e?-1!==a.data.indexOf("__cmpCall")?JSON.parse(a.data):{}:a.data).__cmpCall){var b=c.__cmpCall;window.__cmp(b.command,b.parameter,function(c,m){c={__cmpReturn:{returnValue:c,success:m,callId:b.callId}};a.source.postMessage(e?JSON.stringify(c):c,"*")})}}var e=document.createElement("script");e.src="https://quantcast.mgr.consensu.org/cmp.js",e.async=!0,e.type="text/javascript";
var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(e,b);!function E(){if(!window.frames.__cmpLocator)if(document.body){var a=document.body,c=document.createElement("iframe");c.style="display:none",c.name="__cmpLocator",a.appendChild(c)}else setTimeout(E,5)}(),window.__cmp=function(a){var c=arguments;if(!c.length)return window.__cmp.a;if("ping"===c[0])c[2]({gdprAppliesGlobally:!1,cmpLoaded:!1},!0);else{if("__cmp"===a)return!1;void 0===window.__cmp.a&&(window.__cmp.a=[]),window.__cmp.a.push([].slice.apply(c))}},
window.__cmp.gdprAppliesGlobally=!1,window.__cmp.msgHandler=a,window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent("onmessage",a);(e=m())?window.__cmp("init",e):window.__cmp("init",{Language:"en","Initial Screen Reject Button Text":"I do not accept","Initial Screen Accept Button Text":"I accept","Purpose Screen Body Text":"You can set your consent preferences and determine how you want your data to be used based on the purposes below. You may set your preferences for us independently from those of third-party partners. Each purpose has a description so that you know how we and partners use your data.",
"Vendor Screen Body Text":"You can set consent preferences for each individual third-party company below. Expand each company list item to see what purposes they use data for to help make your choices. In some cases, companies may disclose that they use your data without asking for your consent, based on their legitimate interests. You can click on their privacy policies for more information and to opt out.","Vendor Screen Accept All Button Text":"Accept all","Vendor Screen Reject All Button Text":"Reject all",
"Initial Screen Body Text":"We and our partners use technology such as cookies on our site to personalise content and ads, provide social media features, and analyse our traffic. Click below to consent to the use of this technology across the web. You can change your mind and change your consent choices at anytime by returning to this site.","Initial Screen Body Text Option":1,"Publisher Name":"Newsarama","Publisher Logo":"https://www.dropbox.com/s/31kj7zycqanrcko/Capture%20d%E2%80%99%C3%A9cran%202019-06-11%20%C3%A0%2014.23.29.png?raw=1",
"Consent Scope":"service","No Option":!1});e=document.createElement("style");e.innerText="\n  .qc-cmp-button {\n    background-color: #1a98ee !important;\n    border-color: #1a98ee !important;\n  }\n  .qc-cmp-button:hover {\n    background-color: transparent !important;\n    border-color: #1a98ee !important;\n  }\n  .qc-cmp-alt-action,\n  .qc-cmp-link {\n    color: #1a98ee !important;\n  }\n  .qc-cmp-button {\n    color: #000000 !important;\n  }\n  ",document.head.appendChild(e)};var r=function(){return Object(t.a)(Object(d.a)("newsarama.com|laptopmag.com|cyclingnews.com"))||
-1!==document.location.search.indexOf("cmp=quantcast")},l=function(){var a=q.a.get("cmp_choice");a||(a=function(){var a,c=m().distribution,c=(a=[]).concat.apply(a,b()(c.map(function(a){return Array(a.ratio).fill(a)})));return c[Math.floor(Math.random()*c.length)]}().mode,q.a.set("cmp_choice",a));return a},p=function(){return!!r()&&"quantcast"===l()},n=function(){if(r()){var a=function(){var a=m().distribution;if(!a)return null;var c=l();return a.find(function(a){return a.mode===c})}();a.experiment&&
window.googletag.pubads().getSlots().forEach(function(c){return c.setTargeting("experiment",a.experiment)})}}},function(f,g,a){f={get:function(a){a=("; "+document.cookie).split("; "+a+"=");if(2===a.length)return a.pop().split(";").shift()},getAll:function(){return document.cookie.split("; ").reduce(function(a,d){var b=d.indexOf("=");return a[d.substr(0,b)]=d.substr(b+1),a},{})},set:function(a,d,f,q){var b=new Date;b.setTime(b.getTime()+1E3*f);a=["".concat(a,"=").concat(d),"expires=".concat(b.toUTCString()),
"path=/"];q&&a.push("domain=".concat(q)),document.cookie=a.join(";")}};g.a=f},function(f,g,a){f=a(1);var b=a.n(f);f=a(2);var d=a.n(f),t=function(){function a(m){b()(this,a),this.name=m,this.callbacks=[]}return d()(a,[{key:"registerCallback",value:function(a){this.callbacks.push(a)}}]),a}();a=function(){function a(){b()(this,a),this.events={}}return d()(a,[{key:"dispatchEvent",value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');this.events[a]&&this.events[a].callbacks.forEach(function(a){a(b)})}},
{key:"addEventListener",value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');if("function"!=typeof b)throw new Error('"callback" must be a function');this.events[a]=this.events[a]||new t(a),this.events[a].registerCallback(b)}},{key:"removeEventListener",value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');if("function"!=typeof b)throw new Error('"callback" must be a function');this.events[a]&&-1!==this.events[a].callbacks.indexOf(b)&&
this.events[a].callbacks.splice(this.events[a].callbacks.indexOf(b),1)}}]),a}();g.a=new a},,function(f,g,a){var b=a(16),d=a(17),t=a(18);f.exports=function(a,f){return b(a)||d(a,f)||t()}},,function(f,g,a){function b(a){var c=window.purchs2s.dfpInfos;if(c&&c[a]&&c[a].dfpLineItemId){var e=c[a].dfpLineItemId;return Object.entries(c).filter(function(a){a=E()(a,2);a[0];return a[1].dfpLineItemId===e}).map(function(a){a=E()(a,2);var c=a[0];a[1];return c})}return[]}function d(){return window.purchs2s?function(a){return window.purchs2s.bidResponse&&
window.purchs2s.bidResponse.bids&&window.purchs2s.bidResponse.bids.find(function(c){return c.divid===a})&&window.purchs2s.bidResponse.bids.find(function(c){return c.divid===a}).rtbSold}.apply(void 0,arguments):y.a.apply(void 0,arguments)}function t(){return window.purchs2s?function(a){return window.purchs2s.bidResponse&&window.purchs2s.bidResponse.bids&&window.purchs2s.bidResponse.bids.find(function(c){return c.divid===a})&&window.purchs2s.bidResponse.bids.find(function(c){return c.divid===a}).bdrid}.apply(void 0,
arguments):y.d.apply(void 0,arguments)}function q(){return window.purchs2s?function(a){return window.purchs2s.dfpInfos&&window.purchs2s.dfpInfos[a]&&window.purchs2s.dfpInfos[a].dfpCampaignId}.apply(void 0,arguments):y.f.apply(void 0,arguments)}function m(){return window.purchs2s?function(a){return window.purchs2s.dfpInfos&&window.purchs2s.dfpInfos[a]&&window.purchs2s.dfpInfos[a].dfpLineItemId}.apply(void 0,arguments):y.e.apply(void 0,arguments)}function r(){return window.purchs2s?function(a){if(window.purchs2s.refresh&&
(window.purchs2s.refresh(a),window.purchs2s.disablePurchS2SDFPRefresh&&window.headertag)){var c=window.googletag.pubads().getSlots().filter(function(c){return c.getSlotElementId()===a});window.headertag.cmd.push(function(){window.headertag.refresh(c)})}}.apply(void 0,arguments):y.c.apply(void 0,arguments)}function l(){return!!window.purchs2s&&function(a){return 3<=b(a).length}.apply(void 0,arguments)}function p(a){u("Reinitializing ".concat(G(M)," timer"),a.id),a.autorefreshTimers&&a.autorefreshTimers.stop(),
a.autorefreshTimers=new B(M,w,a.id,function(){!function(a){var c=document.querySelector("#".concat(a));if(c.refreshCount++,delete c.viewableTimer,delete c.canRefresh,!function(a,c){if(C<c)return u("Enough refreshes, this one was the last one",a),!1;if(l(a))return u("Currently displaying a roadblock so we don't refresh",a),u("Adunits used by the roadblock: ".concat(function(){return window.purchs2s?b.apply(void 0,arguments):[]}(a).join(", "))),!1;if(!d(a)){if(!N)return u("Can't refresh, ADX refresh is disabled",
a),!1;c=q(a);var e=m(a);return c?K.includes(c)?(u("Can't refresh, ad has not been served by RAMP and its DFP Order ID (".concat(c,") is in the unrefreshable DFP Orders list"),a),!1):H.includes(e)?(u("Can't refresh, ad has not been served by RAMP and its Line Item ID (".concat(e,") is in the unrefreshable DFP LineItems list"),a),!1):(u("Can refresh, ad has not been served by RAMP, but its DFP Order ID (".concat(c,") and its DFP Line Item ID (").concat(e,") are not in the unrefreshable DFP Orders and DFP LineItems lists"),
a),!0):(u("Can't refresh, ad has not been served by RAMP and its DFP Order ID is null",a),!1)}c=t(a);return u("Bidder ID: ".concat(c||"null"),a),-1!==F.indexOf(c)||(u("Can't refresh, it's currently displaying an ad from bidder ".concat(c),a),!1)}(a,c.refreshCount))return c.refreshable=!1;u("Refreshing (refresh #".concat(c.refreshCount,")"),a),r(a,c),p(c)}(a.id)}),A.a.is(a)&&Object(A.a)("#".concat(a.id)).emit("enter",a)}function n(a){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};
M=c.refreshDelay||3E4,w=c.viewableDelay||1E4,C=c.limit||4,F=c.refreshableBiddersIds||[],K=c.unrefreshableOrders||[],H=c.unrefreshableLineItems||[],N=c.ADXRefreshEnabled||!1,(u=c.debug?u:function(){})("Configuration:"),u("Refresh delay: ".concat(G(M))),u("Viewable delay: ".concat(G(w))),u("Refresh limit: ".concat(C)),u("Refreshable bidders: ".concat(F.join(", "))),u("ADX refresh enabled: ".concat(N)),u("Unrefreshable Orders: ".concat(K.join(", "))),u("Unrefreshable LineItems: ".concat(H.join(", "))),
u("Adunits selected for autorefresh: ".concat(a.join(", "))),a.forEach(function(a){var c="#".concat(a),e=document.querySelector(c);e&&(e.refreshCount=e.refreshCount||0,e.refreshable=!0,Object(A.a)(c).on("enter",function(c){c.autorefreshTimers.entersViewport(),u("Adunit just entered viewport. ".concat(G(c.autorefreshTimers.remaining()[0])," left in refresh timer. ").concat(G(c.autorefreshTimers.remaining()[1])," left in viewability timer."),a)}).on("exit",function(c){c.autorefreshTimers.leavesViewport(),
u("Adunit just left viewport. ".concat(G(c.autorefreshTimers.remaining()[0])," left in refresh timer. ").concat(G(c.autorefreshTimers.remaining()[1])," left in viewability timer."),a)}),p(e))}),v()}f=a(1);var c=a.n(f);f=a(2);var e=a.n(f),A=a(7),y=a(0);f=a(13);var E=a.n(f),z=a(11);a.d(g,"a",function(){return n});var M,w,F,C,K,H,N,u=function(a,c){var e=c?"[".concat(c,"] "):"";c=c?"text-transform: uppercase; font-size: smaller; font-weight: bold; color: black; background-color: orange; padding: .2em 0em; border-radius: 3px; margin: 0 3px":
"";console.log("%cAutorefresh [".concat((new Date).toLocaleTimeString(),"]%c ").concat(e,"%c").concat(a),"text-transform: uppercase; font-size: smaller; font-weight: bold; color: white; background-color: black; padding: .2em .5em; border-radius: 3px",c,"")},G=function(a){return"".concat(a/1E3,"s")},O=function(){function a(e,b){c()(this,a),this.remainingTime=b,this.paused=!1,this.callback=e,this.resume()}return e()(a,[{key:"pause",value:function(){window.clearTimeout(this.timerId),this.remainingTime-=
new Date-this.start,this.paused=!0}},{key:"resume",value:function(){this.start=new Date,window.clearTimeout(this.timerId),this.timerId=window.setTimeout(this.callback,this.remainingTime),this.paused=!1}},{key:"remaining",value:function(){return this.paused?Math.max(0,this.remainingTime):Math.max(0,this.remainingTime-(new Date-this.start))}}]),a}(),B=function(){function a(e,b,D,n){var v=this;c()(this,a),this.inView=!1,this.viewableTimerFinished=!1,this.refreshTimerFinished=!1,this.refreshDelay=e,this.viewableDelay=
b,this.divId=D,this.callback=n,this.refreshTimer=new O(function(){v.refreshTimerFinished=!0,v.executeCallback()},this.refreshDelay)}return e()(a,[{key:"entersViewport",value:function(){var a=this;return this.inView=!0,this.viewableTimerFinished?this.executeCallback():(this.viewableTimer?this.viewableTimer.resume():this.viewableTimer=new O(function(){a.viewableTimerFinished=!0,a.executeCallback()},this.viewableDelay),null)}},{key:"leavesViewport",value:function(){this.inView=!1,this.viewableTimer.pause()}},
{key:"executeCallback",value:function(){this.refreshTimerFinished&&this.viewableTimerFinished&&this.inView&&(u("adunit has spend ".concat(G(this.viewableDelay)," in view and ").concat(G(this.refreshDelay)," timer is finished and element is in view, we can try to refresh it"),this.divId),this.callback())}},{key:"stop",value:function(){this.refreshTimer&&this.refreshTimer.pause(),this.viewableTimer&&this.viewableTimer.pause()}},{key:"remaining",value:function(){return[this.refreshTimer.remaining(),
this.viewableTimer.remaining()]}}]),a}(),I,J,v=(J=!(I=function(){z.a.addEventListener("refresh",function(a){a&&a.divIds&&!a.trn&&a.divIds.forEach(function(a){a=document.getElementById(a);a.autorefreshTimers&&(a.autorefreshTimers.stop(),p(a))})})}),function(){var a;return J||(a=I.apply(void 0,arguments)),J=!0,a})},function(f,g){f.exports=function(a){if(Array.isArray(a))return a}},function(f,g){f.exports=function(a,b){var d=[],f=!0,g=!1,m=void 0;try{for(var r,l=a[Symbol.iterator]();!(f=(r=l.next()).done)&&
(d.push(r.value),!b||d.length!==b);f=!0);}catch(p){g=!0,m=p}finally{try{f||null==l.return||l.return()}finally{if(g)throw m;}}return d}},function(f,g){f.exports=function(){throw new TypeError("Invalid attempt to destructure non-iterable instance");}},function(f,g,a){a.d(g,"b",function(){return d}),a.d(g,"a",function(){return t});var b=function(a){var b=[];return a.forEach(function(a){window.tmntag.slots[a]&&b.push(window.tmntag.slots[a])}),b},d=function(a,f,d){var g=function(a,e){var c=a.account;if(c)if((c=
c.split("/"))&&0<c.length){var b=c.reverse()[0];if(0<b.indexOf("-")){if((b=b.split("-"))&&0<b.length)for(var d=0;d<b.length;d++){var n=b[d];if(0==n.indexOf("p")){n=n.substring(1);isNaN(n)||(n=1*n+(e+1),b[d]="p"+n)}}c[0]=b.join("-"),a.account=c.reverse().join("/")}}},m=function(a){var c=a.targeting||{},b;for(b in c)c.hasOwnProperty(b)&&"_p"===b&&c[b]&&(a.targeting[b]=1*c[b]+1)};if(!("JSON"in window))return!1;var n=[];if(a.forEach(function(a){var c=a.divId;a=a.cloneDivId;var b=function(a,c){var b=window.tmntagCache.filter(function(c){return c.div&&
0===c.div.indexOf(a)});return 0!=b.length&&(c&&c.resetPosition?b[0]:b[b.length-1])}(c,d);if(!b)return!1;for(var l=a.constructor===Array?a:[a],q=[],t=0,p=0;p<l.length;p++){var w=void 0;a=l[p];try{w=JSON.parse(JSON.stringify(b))}catch(C){return!1}if(w.div=a,w.targeting=w.targeting||{},f)for(var r in f)f.hasOwnProperty(r)&&f[r]&&(w.targeting[r]=f[r]);window.tmntag.adparams=window.tmntag.adparams||{},window.tmntag.adparams[a]=window.tmntag.adparams[c],d&&d.disableIncrementAccountPosition||(d&&!d.resetPosition||
0<p)&&g(w,t++),d&&d.disableIncrementPosition||b.disableIncrementPosition||m(w),window.tmntag.adunit(w),b.adunitRule&&window.tmntag.getAdParameters(c)&&"true"===window.tmntag.getAdParameters(c).on_clone_execute_preadunitrender&&b.adunitRule.apply(null,[a]);w=window.tmntag_defineSlot(a,w.targeting);n.push(a),q.push(w)}window.tmntag.events.dispatchEvent("adunitCloned",{originalDivId:c,clonedDivIds:n})}),d&&d.disableRefreshRamp)window.googletag.cmd.push(function(){for(var a=0;a<n.length;a++)window.googletag.display(n[a]);
window.tmntag_initialLoadDisabledMode&&window.googletag.pubads().refresh(b(n))});else{a=d&&d.pageUrl||"";window.tmntag.start(!0,n,function(){window.googletag.cmd.push(function(){for(var a=0;a<n.length;a++)window.googletag.display(n[a]);window.tmntag_initialLoadDisabledMode&&window.googletag.pubads().refresh(b(n))})},null,null,null,!0,a)}},t=function(a,b,f,g){return d([{divId:a,cloneDivId:b}],f,g)}},function(f,g,a){f.exports=a(32)},function(f,g,a){var b=a(0);g.a=function(a){var d=document.getElementById(a);
return!(!d||"true"!==Object(b.g)(a,"sticky"))&&(d.style.position="sticky",d.style.top="0",d.parentNode.style.height="100%",!0)}},function(f,g,a){var b=a(0);g.a=function(a){if("true"!==Object(b.g)(a,"anchor"))return!1;var f=document.getElementById.bind(document),d=window.GUMGUM;d&&d.isad&&d.isad.closeAd();var g=f(a);if(function(a){var c=window.tmntag;return c&&c.markupsInfo&&c.markupsInfo[a]&&"48"===c.markupsInfo[a].bidderid&&c.markupsInfo[a].rtbSold}(a))return g&&(g.style.display="none"),!0;if(!g)return console.error("-- RAMP --- Element Not Found in DOM ".concat(a)),
!1;g.classList.add("purch-anchor-adunit");var r,l=Object(b.g)(a,"anchor.bottomOffset")||0;if(d=Object(b.g)(a,"anchor_cookieBannerSelector")){var p=document.querySelector(d);if(p)r=p.getBoundingClientRect().height,l+=r,(new MutationObserver(function(a){a.forEach(function(a){a=Array.prototype.slice.call(a.removedNodes);(-1<a.indexOf(p)||a.find(function(a){return a.contains(p)}))&&(g.style.bottom="".concat(l-r,"px"))})})).observe(document.body,{subtree:!0,childList:!0})}Object.assign(g.style,{position:"fixed",
bottom:"".concat(l,"px"),zIndex:g.style.zIndex||"1000",display:"block",width:"100%",left:0,textAlign:"center",backgroundColor:"rgba(255, 255, 255, .8)",boxShadow:"0 -1px 1px 0 rgba(0, 0, 0, .2)",paddingTop:"5px"}),function(){var a=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,b=window.devicePixelRatio||1,d=window.screen.width*b,b=window.screen.height*b;return a&&(1125===d&&2436===b||828===d&&1792===b||1242===d&&2688===b)}()&&l<15&&(g.style.bottom="15px");var d="tmn-mobile-anchor-close-button-link-id_".concat(a),
n=f(d);return n||((n=document.createElement("a")).addEventListener("click",function(){f(a).style.display="none"}),n.innerHTML="&times;",n.id=d,Object.assign(n.style,{fontFamily:"sans-serif",color:"#b2b2b2",backgroundColor:"rgba(255, 255, 255, .5)",textDecoration:"none",borderRadius:"50%",position:"absolute",right:"5px",textAlign:"center",display:"none",width:"20px",height:"20px",lineHeight:"20px",border:"1px solid #b2b2b2",top:"8px"})),g.appendChild(n),setTimeout(function(){n.style.display="inline-block"},
3E3),!0}},function(f,g,a){var b=a(29),d=a(30),t=a(31);f.exports=function(a){return b(a)||d(a)||t()}},function(f,g,a){a.d(g,"a",function(){return l});f=a(1);var b=a.n(f);f=a(2);var d=a.n(f),t=a(10),q=a(5),m=a(3),r=a(4),l=function(){function a(){b()(this,a),this.cookiesMap=t.a.getAll()}return d()(a,[{key:"create",value:function(a,c,b,d,f){var e=this,n="usp.".concat(a);this.cookiesMap[n]||Object(m.a)(c,function(){var a=Object(r.a)(b);Object(q.a)(a)===d&&function(a,c){a&&-1!==["IFRAME","IMG","SCRIPT"].indexOf(a.tagName)?
(a.addEventListener("load",function(){return c(a)}),a.addEventListener("error",function(){return c(a)})):c(a)}(f(),function(){return e.refreshCookie(n)})})}},{key:"refreshCookie",value:function(a){var c;2<document.location.hostname.split(".").length&&(c=document.location.hostname.split(".").slice(1).join(".")),t.a.set(a,1,"604800",c),this.cookiesMap[a]=1}}]),a}()},function(f,g){function a(a,d,f,g,m,r,l){try{var b=a[r](l),n=b.value}catch(c){return void f(c)}b.done?
d(n):Promise.resolve(n).then(g,m)}f.exports=function(b){return function(){var d=this,f=arguments;return new Promise(function(g,m){function q(b){a(p,g,m,q,l,"next",b)}function l(b){a(p,g,m,q,l,"throw",b)}var p=b.apply(d,f);q(void 0)})}}},function(f,g,a){var b=function(a,c){return Promise.race([new Promise(a),new Promise(function(a){window.setTimeout(a,c)})])};f=a(20);var d=a.n(f);f=a(25);var t=a.n(f),q=a(0),m={init:function(){var a=t()(d.a.mark(function e(a,b){return d.a.wrap(function(e){for(;;)switch(e.prev=
e.next){case 0:return e.next=2,new Promise(function(a){var b=document.createElement("script");b.src="https://static.adsafeprotected.com/vans-adapter-google-ima.js",b.addEventListener("load",a),document.body.appendChild(b)});case 2:a.on("adsManager",function(a){var e=a.adsManager;a=a.videoElement;var d={anId:"923193",campId:Object(q.h)()?"480x270":"640x480",chanId:b};window.googleImaVansAdapter.init(window.google,e,a,d)});case 3:case "end":return e.stop()}},e)}));return function(b,d){return a.apply(this,
arguments)}}()},r=function(a,c,b){return b=b||{},a.reduce(function(a,b){return-1!==c.indexOf(b[0])&&(a[b[0]]=b[1]),a},b)},l={settings:{},status:{},logError:function(a){if(l.triggerErrorEventEnabled){var c={};tmntag.pubtargets&&(c=r(tmntag.pubtargets,["_rid"],c)),window.tmntag_triggerEvent("VE",{crid:a.code,ad:encodeURIComponent(a.tag),id:c._rid})}console.log("-RAMP VIDEO- Error",a)}},p=function(a,c,b){c={};tmntag.markupsInfo&&tmntag.markupsInfo[b]&&(c.bidderid=tmntag.markupsInfo[b].bidderid,c.adomain=
tmntag.markupsInfo[b].adomain),tmntag.vadtargets&&tmntag.vadtargets[b]&&(c=r(tmntag.vadtargets[b],["_cp","_pl","_pdid","_wb","_puids"],c)),tmntag.pubtargets&&(c=r(tmntag.pubtargets,["_ex","_rid"],c));b=c.bidderid||"3003";var e=c._pdid||"",d=c._puids||"",f=c.adomain||"",g=c._wb||"",n=c._cp||"",l=c._pl||"";window.tmntag_triggerEvent(a,{id:c._rid,pdid:e,puids:d,bid:g,cp:n,pl:l,z:"540x304",bdrid:b,ad:encodeURIComponent(f),e:c._ex,l:encodeURIComponent(window.tmntag_topLocation())})};l._videoView=function(a,
c){p("VV",0,c),console.log("-RAMP VIDEO- Video View",a)},l._videoServed=function(a,c){p("VS",0,c),console.log("-RAMP VIDEO- Video Served",a)},window.tmntag_videoBeforePlayListItem=function(a,c,e){if(console.log("-RAMP Video- tmntag_videoBeforePlayListItem"),void 0!==l.disableAds&&l.disableAds)console.log("-RAMP Video- Video Ads Disabled");else{var d=c.createInstream().init();(new b(function(c){tmntag.vadtargets=[],tmntag.markupsInfo=tmntag.markupsInfo||{},tmntag.markupsInfo[a]=[],void 0===l.status[a].fetch_count&&
(l.status[a].fetch_count=0);var b=window.tmntag_getAdunitFromCache(a);if(void 0===b||!b){b={div:e.div,sizes:[540,304]};void 0!==e.account&&e.account&&(b.account=e.account),void 0!==l.status[a].player_settings&&(b.targeting={apv:l.status[a].player_settings.autostart?1:0}),tmntag.adunit(b)}tmntag.videoRefresh(e.div,function(){c()})},3E3)).then(function(){d.destroy();var a=l.adTag(e.div,c.id);a?c.playAd(a):c.play()})}},l.setup=function(a,c,b){a&&a.div&&a.account&&(tmntag.account(a.account),tmntag.adunit({div:a.div,
sizes:[540,304]}),l.start(a.div,c,b,a.div,!0))},l.start=function(a,c,b,d,f){void 0!==c.advertising&&c||(c.advertising={client:"googima"}),"string"==typeof d?d={div:d}:void 0===d&&(d={div:a}),tmntag.instartlogicEnabled()&&(c.advertising.client="vast"),c.advertising.autoplayadsmuted=!0,c.advertising.vpaidcontrols=!0,c.advertising.creativeTimeout=2E4,c.advertising.requestTimeout=2E4,c.advertising.loadVideoTimeout=2E4,c.advertising.adsRequestTimeout=2E4,c.advertising.requestTimeout=2E4,c.advertising.maxRedirects=
6,f&&b.setup(c),l.status[a]={},l.status[a].errors=[],l.status[a].impressions=[],l.status[a].player_settings=c,(l.status[a].player=b).on("adError",function(e){"true"===tmntag._config.video_pause_on_error?(l.logError(e),l.status[a].errors.push(e),c.autostart=!1,b.setup(c),b.on("playlistItem",function(){b.once("beforePlay",function(){l._videoView("event",d.div),window.tmntag_videoBeforePlayListItem(a,b,d)})}),b.on("adImpression",function(c){l._videoServed(c,d.div),l.status[a].impressions.push(c)})):
(l.logError(e),l.status[a].errors.push(e))}),b.on("adImpression",function(c){l._videoServed(c,d.div),l.status[a].impressions.push(c)}),b.on("playlistItem",function(){b.once("beforePlay",function(){l._videoView(event,d.div),window.tmntag_videoBeforePlayListItem(a,b,d)})}),"googima"===c.advertising.client&&m.init(b,a)},l.autostarted=function(a,c){l.status[a]&&l.status[a].player_settings&&(l.status[a].player_settings.autostart=c)},l.adTag=function(a,c){var b;return b=tmntag.instartlogicEnabled()?function(){var a=
tmntag.vadtargets,c=0,b=0;if(void 0!==a)for(var d in a)for(var e=a[d],f=0;void 0!==e&&f<e.length;f++){if("_vst"===e[f][0]){var g=e[f][1];if(1<(g=g.split("/")).length)c=g[g.length-2]+"/"+g[g.length-1]}"_vrg"===e[f][0]&&(b=e[f][1])}a="s3.amazonaws.com/purch-us-standard-adserver-prod";"or"===b?a="s3-us-west-2.amazonaws.com/purch-us-west-2-adserver-prod":"eu"===b&&(a="s3-eu-west-1.amazonaws.com/purch-eu-west-1-adserver-prod");b=Math.floor(11E3*Math.random());d="";return c&&(d="https://"+a+"/vast/"+c+
"?cb="+b),d}():function(a,c){var b,d="",e=window.tmntag_getAdunitFromCache(a);if(e&&e.account)d=e.account;else{var f=window.tmntag_getAdUnit(a);f&&f.s?d=f.s:void 0!==tmntag.s&&tmntag.s&&(d=tmntag.s)}b=tmntag.l&&1==tmntag.su?tmntag.l.replace("%",""):encodeURIComponent(window.tmntag_topLocation().replace("%",""));var f=tmntag.vadtargets,g=tmntag.pubtargets;a=tmntag.adtargets[a];var d=["sz="+(Object(q.h)()?"480x270":"640x480"),"iu="+d,"ciu_szs=728x90,300x250","impl=s","gdfp_req=1","env=vp","output=xml_vast3",
"unviewed_position_start=1","url="+b,"correlator=__timestamp__"],l=["plID="+c,"ttID=__item-mediaid__","vdbl=yes","vvid_title=__item-title__","pos=preroll","max_ad_duration=30000"];e.targeting&&Object.keys(e.targeting).forEach(function(a){l.push(a+("="+e.targeting[a]))});c=!1;if(void 0!==g)for(var m in g)l.push(g[m][0]+"="+g[m][1]);if(void 0!==a)for(var n in a)l.push(a[n][0]+"="+a[n][1]);if(void 0!==f)for(var p in f){m=f[p];for(n=0;void 0!==m&&n<m.length;n++){if("_vst"===m[n][0]){c=m[n][1];if(1<(c=
c.split("/")).length){c=c[c.length-2]+"/"+c[c.length-1];l.push("_vst="+c)}}else l.push(m[n][0]+"="+m[n][1]);c=!0}if(c)break}return"https://pubads.g.doubleclick.net/gampad/ads?"+d.join("&")+"&cust_params="+encodeURIComponent(l.join("&"))}(a,c),console.log("-RAMP VIDEO- Video Tag: "+b),b};g.a=l},function(f,g,a){var b=a(4),d=a(5),t=a(9);g.a=function(a){if(Object(t.d)())Object(t.a)();else{var f=Object(b.a)("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr"),g=Object(b.a)("guitarworld.com|loudersound.com|anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com|technobuffalo.com|computing.net");
(Object(d.a)(f)||a.gdprUser&&Object(d.a)(g))&&(a.__cmp=a.__cmp||function(){(window.attachEvent||window.addEventListener)("message",function(a){window.__cmp.receiveMessage(a)},!1),function c(){if(!window.frames.__cmpLocator)if(document.body){var a=document.createElement("iframe");a.style.display="none",a.name="__cmpLocator",document.body.appendChild(a)}else setTimeout(c,5)}();var a=[],b=function(c,b,d){"ping"===c?d&&d({gdprAppliesGlobally:Boolean(window.__cmp&&window.__cmp.config&&window.__cmp.config.storeConsentGlobally),
cmpLoaded:!1}):a.push({command:c,parameter:b,callback:d})};return b.commandQueue=a,b.receiveMessage=function(a){var c="string"==typeof a.data,b={};try{b=c?JSON.parse(a.data):a.data}catch(E){}if(b.__cmpCall){var d=b.__cmpCall;window.__cmp(d.command,d.parameter,function(b,e){b={__cmpReturn:{returnValue:b,success:e,callId:d.callId}};a.source.postMessage(c?JSON.stringify(b):b,"*")})}},b}())}}},function(f,g,a){function b(){if(!H){H=!0;for(var a=0;a<K.length;a++)K[a].fn.call(window,K[a].ctx);K=[]}}function d(){"complete"===
document.readyState&&b()}a.r(g);f=a(8);var t=a.n(f),q=a(19),m=a(3);f=a(24);g=a(15);var r=a(10),l=a(5),p=a(4),n=a(26),c=a(21),e=a(0),A=a(7),y=a(11),E=a(33);a.n(E);var E=a(27),z=a(9),M=a(22);window.TMNAPI_VERSION="tmnhead-5.25.1",window.TMNTAG_VERSION="1.4",window.TMNTAGVIDEOREFRESH_VERSION="1.0vr",window.PREBID_TIMEOUT=200,window.googletag=window.googletag||{},window.googletag.cmd=window.googletag.cmd||[];var w=function(a){window.tmntag.timing&&window.tmntag.timing.startTag&&window.tmntag.timing.loadTag&&
(window.tmntag.timing.adunits[a]=window.tmntag.timing.adunits[a]||[],window.tmntag.timing.adunits[a].push({adLoadTime:(new Date).getTime()-window.tmntag.timing.startTag,tagLoadTime:window.tmntag.timing.startTag-window.tmntag.timing.loadTag}))};window.tmntag_getAdUnitTiming=function(a){var k=window.tmntag.timing;return k&&k.adunits&&k.adunits[a]?window.tmntag.timing.adunits[a][window.tmntag.timing.adunits[a].length-1]:{adLoadTime:0,tagLoadTime:0}};a=function(){return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,
function(a){var k=16*Math.random()|0;return("x"===a?k:3&k|8).toString(16)})};window.defuuid=a(),window.tmntag=window.tmntag||{},window.tmntag.cookies=r.a,window.tmntag._config=window.tmntag._config||{},window.tmntag.config=window.tmntag.config||{},window.tmntag.config.get=function(a,h){return window.tmntag._config[a]||h},Object(E.a)(window);var F=function(a,h){var k=document.createElement("script");k.async=Boolean(h),k.type="text/javascript",k.src=a;(a=document.getElementsByTagName("script")[0]||
document.getElementsByTagName("body")[0])&&a.parentNode.insertBefore(k,a)},C,K,H,N,u;F("//www.googletagservices.com/tag/js/gpt.js",!0),C=window,K=[],H=!1,N=!1,C.tmntag_ready=function(a,h){H?setTimeout(function(){a(h)},1):(K.push({fn:a,ctx:h}),"complete"===document.readyState||!document.attachEvent&&"interactive"===document.readyState?setTimeout(b,1):N||(document.addEventListener?(document.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",b,!1)):(document.attachEvent("onreadystatechange",
d),window.attachEvent("onload",b)),N=!0))},u=function(){for(var a=0;window.tmntagCache&&a<window.tmntagCache.length;a++)if(window.tmntagCache[a]&&window.tmntagCache[a].isMouseOver){var h=Math.floor(11E3*Math.random()),c="https:"===document.location.protocol?"https://":"http://",b=void 0!==window.context&&window.context||!top.window.experiments?"":top.window.experiments,h="".concat(c,"ads2.servebom.com/event.js?t=CC&id=").concat(top.window.requestid?top.window.requestid:0,"&bid=&cp=0&bdrid=&crid=&e=").concat(b,
"&ad=&r=").concat(h);F(h,!1)}},window.addEventListener&&(window.addEventListener("blur",u),window.addEventListener("focusout",u),window.addEventListener("focus",function(){window.addEventListener("blur",u)}));var G=function(a){for(var k=0;k<window.tmntag.a.length;k++)if(window.tmntag.a[k].d===a)return window.tmntag.a[k];return!1};window.tmntag_getAdUnit=G;var O=function(){var a=new Date,h=function(a){return(a<=9?"0":"")+a},c=a.getDate(),b=a.getFullYear(),d=a.getMonth()+1,e=a.getHours(),f=a.getMinutes(),
a=a.getSeconds();return"".concat(b,"-").concat(h(d),"-").concat(h(c)," ").concat(h(e),":").concat(h(f),":").concat(h(a))},B=function(a){return a.constructor===Array};window.tmntag_isArray=B,window.tmntag_getAdunitFromCache=function(a){return window.tmntagCache.find(function(k){return k.div&&k.div===a})||null},window.tmntag_registerMouseOver=function(a){var k=window.tmntag_getAdunitFromCache(a);a=document.querySelector("#".concat(a," iframe"));k&&a&&(a.addEventListener("mouseover",function(){k.isMouseOver=
!0}),a.addEventListener("mouseout",function(){k.isMouseOver=!1}))};var I=function(a){var k=Object(e.g)(a,"incontent_css_selector");k&&window.MultipleIncontent(a,k,{position:Object(e.g)(a,"incontent_position"),repetitionMob:Object(e.g)(a,"incontent_limit_mobile"),repetitionDesk:Object(e.g)(a,"incontent_limit_desktop"),elementsFormula:Object(e.g)(a,"incontent_elements_formula"),progressive:Object(e.g)(a,"incontent_progressive")})},J=function(a){return!!window.tmntag.instartlogicEnabled()||window.tmntag&&
window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].inline},v=function(a){var h=!1,k=window.tmntag_getAdunitFromCache(a);if(!k||!J(a))return h;I(a);var c=document.getElementById(a);if(!c)return h;var b=window.tmntag.markupsInfo[a];if(b&&k){k="".concat(a,"_tmntag_inline_");(h=document.getElementById(k))&&c.removeChild(h);h=document.createElement("div");h.id=k,h.style.border="0pt none",h.style.display="inline-block",h.style.width="".concat(b.width||0,"px"),h.style.height=
"".concat(b.height||0,"px"),h.style.margin="0px",h.style.padding="0px";var d=b.iframe,k=window.tmntag.markups[a];if(k=k.replace(/'\r\n|\r|\n/gm,""),d||window.tmntag.instartlogicEnabled()){d=document.createElement("iframe");d.frameBorder=0,d.scrolling="no",d.marginwidth=0,d.marginheight=0,d.style.width="".concat(b.width||0,"px"),d.style.height="".concat(b.height||0,"px"),d.style.border="0pt none",d.style.margin="0px 0 0",d.width=b.width||0,d.height=b.height||0,h.appendChild(d),c.appendChild(h);c='<!DOCTYPE html><body marginheight="0" marginwidth="0">'.concat(k,
"</body></html>");d.contentDocument.open(),d.contentDocument.write(c),d.contentDocument.close()}else h.innerHTML=k,c.appendChild(h);window.tmntag.onInlineAdunitRendered({divid:a,size:{width:b.width||0,height:b.height||0}}),h=!0}return h};window.tmntag_inlineMarkup=v,window.tmntag_defineSlot=function(a,h,c){var k,b=G(a),L=window.tmntag_getAdunitFromCache(a);try{if(J(a))return v(a),null}catch(Z){return console&&console.error&&console.error(Z),null}if(c)k=window.tmntag.slots[a];else{if(b.z)k=window.googletag.defineSlot(b.s,
b.z,b.d).addService(window.googletag.pubads()),window.tmntag.ced&&k.setCollapseEmptyDiv(!0,!0);else{k=document.getElementById(b.d);k&&(k.style.height="0px"),k=window.googletag.defineOutOfPageSlot(b.s,b.d).addService(window.googletag.pubads())}b.c&&k.addService(window.googletag.companionAds().setRefreshUnfilledSlots(b.c)),L&&void 0!==L.sizeMapping&&k.defineSizeMapping(L.sizeMapping),window.tmntag.slots[a]=k}if(h=h||b&&b.g)for(var d in h)h.hasOwnProperty(d)&&k.setTargeting(d,h[d]);if(void 0!==window.tmntag.adtargets){a=
window.tmntag.adtargets[b.d];if(void 0!==a&&window.tmntag.localAdtargets&&void 0!==window.tmntag.localAdtargets[b.d])for(h=0;h<window.tmntag.localAdtargets[b.d].length;h++)a.push(window.tmntag.localAdtargets[b.d][h]);c&&k&&k.clearTargeting();for(c=0;k&&void 0!==a&&c<a.length;c++)void 0!==window.tmntag_disablertb&&window.tmntag_disablertb&&"_br"===a[c][0]||k.setTargeting(a[c][0],a[c][1])}return k},window.tmntag_defineAdUnit=function(a){var k=window.tmntag_getAdunitFromCache(a);void 0===k.adunitRule?
1===k.refresh?(window.tmntag_defineSlot(a,{},!0),k.refresh=0):1!==window.tmntag.f&&(window.tmntag_defineSlot(a),I(a)):(1===k.refresh&&(window.tmntag_defineSlot(a,{},!0),k.refresh=0),window.tmntag.enableSingleRequest())};var D=function(){window.tmntag_gptloaded=!0},P=function(){try{var a=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight;return"".concat(a,"x").concat(h)}catch(L){console.error(L)}return null};
window.tmntag_topLocation=function(){try{return window.context&&window.context.location&&window.context.location.href?window.context.location.href:window.top.document.location.href}catch(k){return window.document.referrer}};var R=function(){try{return window.context&&window.context.referrer?window.context.referrer:window.top.document.referrer}catch(k){return""}};C=function(){try{if(navigator.mimeTypes&&0<navigator.mimeTypes.length){var a=navigator.mimeTypes["application/x-shockwave-flash"];if(a&&
a.enabledPlugin)return 1}else if("undefined"!=typeof ActiveXObject)try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.1"),1}catch(h){}}catch(h){console&&console.error&&console.error(h)}return 0};window.tmntag_gptloaded=!1,window.tmntag_callbacks=new function(){this.callback=[],this.callback_executed=[],this.pushCallback=function(a,h){void 0!==h?this.callback.push({callback:a,params:h}):this.callback.push({callback:a})},this.executeCallbacks=function(){var a=this.callback.length;if(0<a)for(var h=
0;h<a;){var c=this.callback[0];void 0!==c.params?c.callback.apply(null,c.params):c.callback(),this.callback.splice(0,1),this.callback_executed.push(c),h++}}},window.tmntag_initialLoadDisabled=!1,window.tmntag_initialLoadDisabledMode=!1,window.tmntagCache=[],window.tmntag.cmd=window.tmntag.cmd||[],window.tmntagDisplayed={},window.tmntag.timing={},window.tmntag.timing.adunits={},window.tmntag.timing.start=(new Date).getTime(),window.tmntag.sr=!0,window.tmntag.ced=!0,window.tmntag.a=[],window.tmntag.slots=
{},window.tmntag.l=encodeURIComponent(window.tmntag_topLocation().replace("%","")),window.tmntag.tt=encodeURIComponent(document.title?document.title.replace("|",""):""),window.tmntag.t=O(),window.tmntag.tz=Math.round((new Date).getTimezoneOffset()),window.tmntag.r=P(),window.tmntag.su=0,window.tmntag.fs=C(),window.tmntag.disabledAdunits=[],window.tmntag.disableDFPRefresh=!1,window.tmntag.onAdunitRenderedCallbackFunction=function(){},window.tmntag.video=n.a,window.tmntag.safeFunctionCall=function(a,
h){return"function"==typeof window[a]?window[a].apply():h||""},window.tmntag.instartlogicEnabled=function(){return window.I11C&&1===window.I11C.Morph},window.tmntag.placementCustomID=function(a){window.tmntag.pc=a},window.tmntag.getAdParameters=e.g,window.tmntag.placement=function(a){window.tmntag.p=a},window.tmntag.account=function(a){a=a&&a.replace(/\t|\s+/gm,""),window.tmntag.s=a};var x=function(a,h,c){for(var k=a.length-1;0<=k;k--){var b=a[k];b[h]&&b[h]===c&&a.splice(k,1)}};window.tmntag.adunit=
function(a){if(window.tmntag.disabledAdunits.find(function(h){return h===a.div}))return null;var h=window.tmntag_getAdunitFromCache(a.div);if(h){for(var c in a)h[c]=a[c];a=h}h={};return a.account?h.s=a.account:window.tmntag.s&&(h.s=window.tmntag.s),a.sizes&&(h.z=a.sizes),a.div&&(h.d=a.div),a.targeting?(h.g=a.targeting,a.atf=a.targeting._a):h.g={},a.atf&&("1"===a.atf?h.a="true":"0"===a.atf&&(h.a="false")),a.companion&&(h.c=a.companion),a.div&&(x(window.tmntag.a,"d",a.div),x(window.tmntagCache,"div",
a.div)),a.sizeMapping&&(h.sm=a.sizeMapping),window.tmntag.a.push(h),window.tmntagCache.push(a),h},window.tmntag.adunitTarget=function(a,h,c){if("object"===t()(a))a.g[h]=c;else if("string"==typeof a){var b=window.tmntag.localAdtargets=window.tmntag.localAdtargets||[];b[a]=b[a]||[],b[a].push([h,c])}},window.tmntag.target=function(a){try{if("object"!==t()(a)||a instanceof Array)return;for(var h in window.tmntag.g||(window.tmntag.g=a),a)if(a.hasOwnProperty(h)){var c=a[h];if(c&&B(c)){for(var b=0;b<c.length;b++)c[b]=
String(c[b]),c[b]=c[b].replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,""),c[b]=c[b].replace(/%/gm,"");window.tmntag.g[h.replace(/'|&|#/g,"")]=c}else c&&(h=h.replace(/'|&|#/g,""),c="".concat(c),window.tmntag.g[h]=c.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,""),window.tmntag.g[h]=window.tmntag.g[h].replace(/%/gm,""))}}catch(aa){console&&console.error&&console.error(aa)}},window.tmntag.location=function(a){window.tmntag.l=encodeURIComponent(a),
window.tmntag.su=1};var U=function(a){var c=Object(e.g)(a);if(c)if(c=c.adunit_style){a=document.getElementById(a);for(var c=c.trim().split(";"),b=0;b<c.length;b++)if(""!==c[b]){var k=c[b].split(":"),d=null;k[1]&&(0<=k[1].indexOf("!important")&&(k[1]=k[1].replace("!important",""),d="important"),a.style.setProperty(k[0].trim(),k[1].trim(),d))}}};window.tmntag.adTag=function(a,c){try{if(window.tmntag.disabledAdunits.find(function(c){return c===a}))return;var b=window.tmntag_getAdunitFromCache(a);if(!b||
null===b)return void(void 0!==c&&!c||document.getElementById(a)?void 0===c?window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a]):window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a,c]):(window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a,!1]),void 0===c&&document.write('<div id="'.concat(a,'"></div>'))));var h=void 0!==b.adunitRule&&"function"==typeof b.adunitRule&&!0===b.adunitRule(a);if(void 0===b.adunitRule||h){if(void 0!==c&&!c||document.getElementById(a)||document.write('<div id="'.concat(a,
'"></div>')),!b.sizes){var k=document.getElementById(a);k&&(k.style.height="0px")}U(a),h?window.googletag.cmd.push(function(){document.getElementById(a)&&window.tmntag?(window.tmntag.slots&&!window.tmntag.slots[a]&&(1===b.refresh?(window.tmntag_defineSlot(a,{},!0),b.refresh=0):window.tmntag_defineSlot(a)),window.googletag.display(a)):window.tmntagDisplayed[a]=1}):window.googletag.cmd.push(function(){document.getElementById(a)&&window.tmntag&&window.tmntag.slots&&window.tmntag.slots[a]?window.googletag.display(a):
window.tmntagDisplayed[a]=1})}}catch(ba){console&&console.error&&console.error(ba)}},window.tmntag.loadScript=function(a,c,b){var h=null!=b,k="function"==typeof c,L=document.createElement("script");L.async=!0,L.src=a;var d;a=document.getElementsByTagName("script")[0];h?d=setTimeout(function(){clearTimeout(d),k&&c()},b):k&&(L.onload=c),a.parentNode.insertBefore(L,a)};var S=function(a,c,b,d){a=(a=a||[])instanceof Array?a:[a];var h=c=c.filter(function(a){return a.d}),k=window.tmntag.markupsInfo;return!d&&
b&&window.tmntag.disableDFPRefresh&&(h=c.filter(function(c){return-1!==a.indexOf(c.d)}).filter(function(a){return k[a.d]&&k[a.d].rtbSold})),0===a.length?h:h.filter(function(c){return-1<a.indexOf(c.d)})};window.tmntag_filterAdUnitsByIds=S;window.tmntag.addCookies=function(){var a={},c=window.tmntag.cookies.get("up_28");void 0!==c&&(a.up_28=c);c=window.tmntag.cookies.get("D_TOKEN");return void 0!==c&&(a.D_TOKEN=c),a},window.tmntag.getParams=function(){return""===window.location.search?{}:window.location.search.substr(1).split("&").reduce(function(a,
c){var b=c.indexOf("=");return a[c.substr(0,b)]=c.substr(b+1),a},{})},window.tmntag.setPersonalizedAdsMode=m.d,window.tmntag.getPersonalizedAdsMode=m.c,window.tmntag_formateMacromapList=p.a,function(){if(!Object(z.d)()){var a=Object(p.a)("fredzone.org|homecinema-fr.com|lemondenumerique.com|tomshw.it"),c=Object(p.a)("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr"),b=Object(p.a)("guitarworld.com|loudersound.com|anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com|technobuffalo.com|computing.net");Object(m.d)("allowed"),Object(l.a)(a)?Object(m.d)("blocked"):Object(l.a)(c)?
Object(m.d)("managed"):window.gdprUser&&(Object(l.a)(b)?Object(m.d)("managed"):Object(m.d)("blocked"))}}(),window.tmntag_serializeState=function(a,c,b,d,e){b={};a=(b.f=a?1:"",b.p=a?"":window.tmntag.p,b.fmt=window.tmntag.fmt||"WEB",b.s=window.tmntag.s,b.g=window.tmntag.g,b.l=window.tmntag.l,b.tt=window.tmntag.tt,b.tt=b.tt.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,""),b.fs=window.tmntag.fs,b.a=S(c,window.tmntag.a||[],a,d),b.t=O(),b.ck=window.tmntag.addCookies(),
b.tz=Math.round((new Date).getTimezoneOffset()),b.r=P());{a:{c=window.tmntag.cookies.get("DigiTrust.v1.identity");if(void 0===c){c=null;break a}c=JSON.parse(atob(decodeURIComponent(c)));c=encodeURIComponent(btoa(JSON.stringify({id:c.id,keyv:c.keyv})))}}a,b.dgt=c,b.rf=encodeURIComponent(R().replace("%","")),b.pam=window.tmntag.getPersonalizedAdsMode(),b.gdpr_consent=e;e=window.tmntag.getParams();a=decodeURIComponent(e.key);if(e.key&&-1!==atob(a).indexOf(",")){e=atob(a).split(",");b.g=b.g||{},b.g.kw=
b.g.kw||[],"string"==typeof b.g.kw&&(b.g.kw=[b.g.kw]),b.g.kw=b.g.kw.concat(e)}return JSON.stringify(b).replace(/'|&|#/g,"")};var V=function(a,c){var b=[];if(void 0!==a){if(a instanceof Array)for(var h in a){var k=window.tmntag.slots[a[h]];k&&b.push(k)}else(h=window.tmntag.slots[a])&&b.push(h);if(0<b.length){for(var d in b)if(b.hasOwnProperty(d)&&c)for(var e in b[d].clearTargeting(),c)c.hasOwnProperty(e)&&b[d].setTargeting(e,c[e]);window.googletag.pubads().refresh(b)}console&&console.info&&console.info("-RAMP- Regular refresh ".concat(a))}else window.googletag.pubads().refresh()};
window.tmntag.refresh=function(a,c,b){a&&(a=B(a)?a:[a]).forEach(function(a){var c=window.tmntag_getAdunitFromCache(a),h=window.tmntag.adtargets[a]&&window.tmntag.adtargets[a].find(function(a){return"_trn"===a[0]});if(void 0===b||c.targeting._trn){if(void 0===b&&c&&c.targeting&&c.targeting._trn&&window.tmntag.adtargets[a]){h=window.tmntag.adtargets[a].indexOf(h);window.tmntag.adtargets[a].splice(h,1),delete c.targeting._trn}}else window.tmntag.adtargets[a]=window.tmntag.adtargets[a]||[],window.tmntag.adtargets[a].push(["_trn",
b]),c.targeting._trn=b});a=S(a,window.tmntag.a||[],!0,!1);for(var h=[],k=0;k<a.length;k++)h.push(a[k].d);h.forEach(function(a){window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&(window.tmntag.markupsInfo[a]={})}),window.tmntag.start(!0,h,function(){V(h,c),window.tmntag.events.dispatchEvent("refresh",{divIds:h,trn:b})})},window.tmntag.refreshPixels=function(){if(void 0!==window.tmntag.tmn_pixels)for(var a=0;a<window.tmntag.tmn_pixels.length;a++){var c=window.tmntag.tmn_pixels[a];c.isRefreshable()&&
c.execute()}},window.tmntag_redirect=function(a,c,b){if(!a)return!1;var h={cp:"__CP__",bdrid:"__BDRID__",crid:"__CRID__",ad:"__AD__",pd:"__PRODUCT_ID__",tid:"__TID__",pvid:"__PVID__"};a="object"===t()(c)?a.href:c;b="object"===t()(c)?c:b;c=Math.floor(11E3*Math.random());var k="https:"===document.location.protocol?"https://":"http://";b="".concat(k,"ramp.purch.com/event.js?t=CL&id=").concat(top.window.requestid?top.window.requestid:0,"&r=").concat(c).concat(function(a){var c="";if(a&&h)for(var b in h)h.hasOwnProperty(b)&&
a.hasOwnProperty(h[b])&&(c+="pd"===b?"&".concat(b,"=|").concat(a[h[b]],"|"):"&".concat(b,"=").concat(a[h[b]]));return c}(b));return F(b,!1),window.open(a,"_blank").focus(),!1},window.tmntag_triggerEvent=function(a,c){var b="";if(c)for(var h in c){""!==b&&(b+="&");var k="".concat(c[h]);-1===k.indexOf("$")&&(b+="".concat(h,"=").concat(k))}h=Math.floor(11E3*Math.random());k=window.tmntag.instartlogicEnabled()?"1":"";b="t=".concat(a,"&r=").concat(h,"&abr=").concat(k,"&").concat(b),"CP"===a&&(c&&c.ts&&
-1===c.ts.indexOf("$")&&(b="".concat(b,"&tm_alt=").concat(Date.now()-c.ts)),window.tmntag.timing&&window.tmntag.timing.startTag&&window.tmntag.timing.loadTag&&(b="".concat(b,"&tm_tlt=").concat(window.tmntag.timing.startTag-window.tmntag.timing.loadTag)));a=document.createElement("script");a.src="//ads2.servebom.com/event.js?".concat(b);b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},window.tmntag_disableAdunit=function(a){window.tmntag.disabledAdunits.push(a)},window.tmntag_enableAdunit=
function(a){window.tmntag.disabledAdunits.splice(window.tmntag.disabledAdunits.indexOf(a),1)},window.tmntag.adunitNew=function(a,c){if(!window.tmntag.disabledAdunits.find(function(c){return c===a.div})){window.tmntag.adunit(a);var b=a.div;window.tmntag_defineSlot(b),window.googletag.display(b),c&&window.tmntag.refresh(b)}},window.tmntag.multipleAdunitClone=q.b,window.tmntag.adunitClone=q.a,window.tmntag.disableSingleRequest=function(){window.tmntag.sr=!1},window.tmntag.disableCollapseEmptyDivs=function(){window.tmntag.ced=
!1},window.tmntag.enableSingleRequest=function(){window.tmntag.sr=!0},window.tmntag.disableInitialLoad=function(){window.tmntag_initialLoadDisabled=!0,window.tmntag_initialLoadDisabledMode=!0},window.tmntag.onInlineAdunitRendered=function(a){var b=a.divid,k=window.tmntag_getAdunitFromCache(b),d={};d.div=b,d.adunit=k,a.size?d.size={width:a.size[0],height:a.size[1]}:d.size={width:0,height:0},d.isEmpty=!1,d.dfpCreativeId="",d.dfpLineItemId="",d.dfpCampaignId="",k.dfpCreativeId="",k.dfpLineItemId="",
k.dfpCampaignId="",d._orig=a,window.tmntag_registerMouseOver(b),void 0!==window.tmntag_adlabel&&window.tmntag_adlabel&&window.tmntag_adlabel.render(b,d),window.tmntag.onAdunitRenderedCallbackFunction(d),k&&k.onAdunitRendered&&"function"==typeof k.onAdunitRendered&&k.onAdunitRendered(a),Object(M.a)(b),Object(c.a)(b),w(b)},window.tmntag.onAdunitRenderedPrivate=function(a){var b=a.slot.getSlotId().getDomId(),d=window.tmntag_getAdunitFromCache(b),k={};if(k.div=b,k.adunit=d,a.size&&1<a.size[0]&&1<a.size[1]?
k.size={width:a.size[0],height:a.size[1]}:window.tmntag.markupsInfo&&window.tmntag.markupsInfo[b]?k.size={width:window.tmntag.markupsInfo[b].width,height:window.tmntag.markupsInfo[b].height}:k.size={width:0,height:0},k.isEmpty=a.isEmpty,k.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,k.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,k.dfpCampaignId=a.campaignId,d&&(d.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,d.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,d.dfpCampaignId=
a.campaignId),k._orig=a,window.tmntag_registerMouseOver(b),void 0!==window.tmntag_adlabel&&window.tmntag_adlabel&&window.tmntag_adlabel.render(b,k),w(b),window.tmntag.adunitServedEvent&&1<k.size.width&&1<k.size.height){var f={};window.tmntag.markupsInfo&&window.tmntag.markupsInfo[b]&&(f.bidderid=window.tmntag.markupsInfo[b].bidderid,f.adomain=window.tmntag.markupsInfo[b].adomain),window.tmntag.adtargets&&window.tmntag.adtargets[b]&&(f=Object(e.b)(window.tmntag.adtargets[b],["_cp","_pl","_pdid","_wb"],
f)),window.tmntag.pubtargets&&(f=Object(e.b)(window.tmntag.pubtargets,["_ex","_rid"],f));var g=f._pdid||"",v=f.adomain||"",D=f._cp||"",l=f._pl||"",m=f.bidderid||"3003",n=window.tmntag_getAdUnitTiming(b);window.tmntag_triggerEvent("AS",{id:f._rid,pdid:g,bid:f._wb,cp:D,pl:l,bdrid:m,ad:encodeURIComponent(v),e:f._ex,l:encodeURIComponent(window.tmntag_topLocation()),z:"".concat(k.size.width,"x").concat(k.size.height),crid:encodeURIComponent(b),tm_alt:n.adLoadTime,tm_tlt:Math.max(0,n.tagLoadTime)})}try{window.tmntag.onAdunitRenderedCallbackFunction(k)}catch(ca){console.log(ca)}d&&
d.onAdunitRendered&&"function"==typeof d.onAdunitRendered&&d.onAdunitRendered(a),Object(M.a)(b),Object(c.a)(b)},window.tmntag.onAdunitViewablePrivate=function(a){a=a.slot.getSlotId().getDomId();(a=window.tmntag_getAdunitFromCache(a))&&(a.viewable=!0)},window.tmntag.onAdunitRendered=function(a){a="function"==typeof a?a:function(){},this.callbacks=this.callbacks||[],this.callbacks.push(a),window.tmntag.onAdunitRenderedCallbackFunction=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=
arguments[c];this.callbacks.forEach(function(a){a.apply(void 0,b)})}.bind(this)},window.tmntag_xhrGet=function(a,b,c){var h=new XMLHttpRequest;h.withCredentials=!0,c&&(h.timeout=c),h.open("GET",a,!0),h.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&b(this.responseText)},h.send(null)};var Q=function(){for(var a=0;a<document.scripts.length;a++){var b=document.scripts[a],c=b.src.indexOf("tmnhead.js");if(0<c)return b.src.substring(0,c)}return"http://ads.servebom.com/"};window.tmntag_executingStart=
!1,window.tmntag.start=function(a,b,c,d,f,e,g,v){function h(a,b){eval("try { ".concat(a," } catch (e) { console.error(e); }"))}function k(a,b,c){window.tmntag_xhrGet(a,function(a){h(a),b()},c)}function L(a,b){return"".concat(a,"tmntag.js?").concat(Object.keys(b).map(function(a){return"".concat(a,"=").concat(b[a])}).join("&"))}v=v||"";var D=function(a,b,c,h,d,g,v){if(g&&window.tmntag.location(g),!window.tmntag_executingStart||a){a||(window.tmntag.enableSingleRequest(),window.googletag.cmd.push(function(){window.googletag.pubads().addEventListener("slotRenderEnded",
function(a){window.tmntag.onAdunitRenderedPrivate(a)}),window.googletag.pubads().addEventListener("impressionViewable",function(a){window.tmntag.onAdunitViewablePrivate(a)})})),window.tmntag_executingStart=!0;var D=Math.floor(11E3*Math.random());g=Q();var l=[];if("undefined"!=typeof amznads&&null!==window.amznads&&"function"==typeof window.amznads.getTokens){var m=window.amznads.getTokens();if(null!==m&&0<m.length){m=m.join();m=m.replace("kindle_pur_3x6","a3x6p100"),l.push({br:6,bs:m})}}if("object"===
("undefined"==typeof prebidSlots?"undefined":t()(prebidSlots))&&null!==window.prebidSlots)for(var n in window.prebidSlots)if(window.prebidSlots.hasOwnProperty(n)){var m=window.prebidSlots[n],q=[],P;for(P in m){var x=m[P];"object"===t()(x)&&q.push("a".concat(x.width,"x").concat(x.height,"p").concat(x.cpm,":").concat(x.ad))}0<q.length&&l.push({br:n,bs:q.join()})}n={};n.v=f||window.TMNTAG_VERSION,n.r=D,n.o=window.tmntag_serializeState(a,b,e,d,v),a&&"v"!==e&&(window.tmntag.f=1);b=S(b,window.tmntag.a||
[],a,d);if(a&&b)for(d=0;d<b.length;d++)(v=window.tmntag_getAdunitFromCache(b[d].d))&&(v.refresh=1);n.uuid=window.defuuid,"undefined"!=typeof Purch&&window.Purch.calypso&&window.Purch.calypso.pvid&&(n.pvid=window.Purch.calypso.pvid),0<l.length&&(n.j=JSON.stringify(l)),n.at=e||"bnj",window.tmntag.instartlogicEnabled()&&(n.abr=1);var p=L(g,n);a?k(p,c,h):window.tmntag.cmd.push(function(){window.tmntag.loadScript(p)}),window.tmntag.timing.loadTag=(new Date).getTime()}};a&&(window.amznads=null),Object(z.d)()?
Object(m.e)().then(Object(m.b)()).then(function(h){var k=h.gdprApplies;h=h.consentData;Object(m.d)(k?"managed":"allowed");var e=k?h:null;"undefined"!=typeof amznads&&window.amznads&&window.amznads.asyncParams?setTimeout(function(){D(a,b,c,d,g,v,e)},window.PREBID_TIMEOUT):(window.PREBID_TIMEOUT=0,D(a,b,c,d,g,v,e))}):"undefined"!=typeof amznads&&window.amznads&&window.amznads.asyncParams?setTimeout(function(){D(a,b,c,d,g,v)},window.PREBID_TIMEOUT):(window.PREBID_TIMEOUT=0,D(a,b,c,d,g,v))},window.tmntag_passback=
function(a,b){if(b){var c=b.split("|");1===c.length&&window.tmntag_render(a,b),4<=c.length&&(window.tmntag_render(a,c[0])||a.write('<script type="text/javascript">google_ad_client = "ca-pub-5787592483766760";\ngoogle_ad_slot = "'+c[3]+'";\ngoogle_ad_width = '+c[1]+";\ngoogle_ad_height = "+c[2]+';\x3c/script><script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>'))}},window.tmntag.videoRefresh=function(a,b){console.log("-RAMP VIDEO- Refresh");var c=function(){};
"function"==typeof b&&(c=b),window.tmntag.start(!0,a,c,null,window.TMNTAGVIDEOREFRESH_VERSION,"v")},window.tmntag.processAdResponse=function(a){window.tmntag_initialLoadDisabled&&(window.tmntag_initialLoadDisabled=!1,window.googletag.cmd.push(function(){V(a)}))};var da=function(a,b,c){var h;return function(){var d=this,k=arguments,e=c&&!h;clearTimeout(h),h=setTimeout(function(){h=null,c||a.apply(d,k)},b),e&&a.apply(d,k)}},ea=function(a){var b=!1;return void 0!==window.tmntag.adtargets&&void 0!==window.tmntag.adtargets[a]&&
window.tmntag.adtargets[a].forEach(function(a){b=b||"_ll"===a[0]&&a[1]}),b},W=function(a,b,c){var h=window.tmntag.markupsInfo[b].width,d=window.tmntag.markupsInfo[b].height;if("function"==typeof confiantWrapWithCallback&&window.CONFIANT_WRAPPER_ID){var k=window.tmntag.markupsInfo[b].biddername,e="purch_".concat(k);c={ad:c,bidder:e,size:"".concat(h,"x").concat(d),cpm:window.tmntag.adtargets[b]&&window.tmntag.adtargets[b].find(function(a){return"_cp"===a[0]})[1]};window.confiantWrapWithCallback(a,c,
"clarium.global.ssl.fastly.net",window.CONFIANT_WRAPPER_ID,function(a,c,k,f,g,v){window.tmntag_triggerEvent("CB",{bdrid:window.tmntag.markupsInfo[b].bidderid||0,tid:"".concat(e,":").concat(h,"x").concat(d),crid:c,ad:a,cp:v.prebid.cpm,id:window.requestid})})||(a.write(c.ad),a.close())}else a.write(c),a.close();(c=window.tmntag.slots[b])&&c.setTargeting("_bd","none");c=window.tmntag.markupsInfo[b];if(c&&(c.rtbSold=!0),a.defaultView&&a.defaultView.frameElement){c="".concat(h,"px");k="".concat(d,"px");
a.defaultView.frameElement.width=c,a.defaultView.frameElement.height=k,top!==self&&self&&self.frameElement&&(self.frameElement.width=c,self.frameElement.height=k)}};window.tmntag_render=function(a,b){var c=!1;if(void 0!==window.tmntag.markups){var h=window.tmntag.markups[b];if(null!=h)if(h=(h=h.replace("a3x6p100","kindle_pur_3x6")).replace(/'\r\n|\r|\n/gm,""),ea(b)){var d=da(function(){var c;{a:{var k=b,e=void 0;c=void 0;if(e=e||0,c=c||"visible",null===document.querySelector("#".concat(k))){c=null;
break a}var f=document.querySelector("#".concat(k)).getBoundingClientRect(),g=Math.max(document.documentElement.clientHeight,window.innerHeight),k=f.bottom-e<0,e=0<=f.top-g+e;c="above"===c?k:"below"===c?e:!k&&!e}}c&&(document.removeEventListener("scroll",d),W(a,b,h))},50);document.addEventListener("scroll",d),d()}else W(a,b,h),c=!0}return c},window.tmntag_ready(function(){if(window.tmntag)for(var a=0;a<window.tmntag.a.length;a++)v(window.tmntag.a[a].d)}),window.tmntag.multipleInContentSelectors=window.tmntag.multipleInContentSelectors||
{},window.tmntag.multipleInContentParams=window.tmntag.multipleInContentParams||{},window.tmntag.multipleInContent=function(a,b){b=b||{};var c=window.tmntag.multipleInContentSelectors[a];!c&&b.selector&&(c=b.selector),b.clone=!0,Object.assign(b,window.tmntag.multipleInContentParams&&window.tmntag.multipleInContentParams[a]||{}),c&&window.MultipleIncontent(a,c,b)};var fa=(X=function(a){window.tmntag.inView(".ramp-incontent-progressive").on("enter",function(b){b.classList.contains("ramp-incontent-progressive")&&
window.tmntag.multipleInContent(a)})},T=!1,function(){var a;return T||(a=X.apply(void 0,arguments)),T=!0,a}),X,T;window.MultipleIncontent=function(a,b,c){function d(a,b,c){a.parentNode&&a.parentNode.removeChild(a),b.insertAdjacentHTML(c,a.outerHTML),U(a.id)}(c=c||{}).position=c.position||"afterend";var h=c[window.tmntag.isMobile()?"repetitionMob":"repetitionDesk"];if(window.tmntag.multipleInContentSelectors[a]=b,window.tmntag.multipleInContentParams=window.tmntag.multipleInContentParams||{},window.tmntag.multipleInContentParams[a]=
c,!a||!b)return!1;var e=[];b=function(a,b){var c=[];try{c=Array.prototype.slice.call(document.querySelectorAll(a))}catch(ga){}if(!b.elementsFormula)return c;a=function(a){var b=a.match(/^(-?\d*)n(\s*(?:\+|-)\s*\d+)?$/);if(!b)return!1;a=b[1]||"1";a=isNaN(a)?"-1":a;b=b[2]||"0";return b=b.replace(/\s/g,""),[Number(a),Number(b)]}(b.elementsFormula);if(!a)return[];var d=a[0],h=a[1];return c.filter(function(a,b){return 0<=(++b-h)/d&&(b-h)/d%1==0})}(b,c);if(b.length){for(var f=0,k=0,g=b.length;k<g;k++)if(b[k].classList.remove("ramp-incontent-progressive"),
!b[k].classList.contains("ramp-incontent"))if(f++,!c.progressive||f<=c.progressive){if(b[k].classList.add("ramp-incontent"),!h||f<=h){if(0===k){var v=document.getElementById(a)||document.createElement("div");v.id=a,d(v,b[k],c.position)}else{var v="".concat(a,"-").concat(k).concat((new Date).getTime()),D=document.createElement("div");D.id=v,D.classList.add("purchrtb-dynamic"),d(D,b[k],c.position),e.push(v)}f===c.progressive-1&&b[k].classList.add("ramp-incontent-progressive")}}else b[k].classList.add("ramp-incontent-progressive");
c.clone&&window.tmntag.adunitClone(a,e,null,{disableRefreshRamp:0,resetPosition:1})}return fa(a),0<b.length};var Y=!1;window.tmntag_onAdTagReady=function(){if(Y);else{{Y=1;for(var a=document.querySelectorAll(".purchrtb-dynamic"),b={},c=0,d=a.length;c<d;c++){var e=a[c].id.lastIndexOf("-");if(0<e){e=a[c].id.substring(0,e);b[e]||(b[e]=[]),b[e].push(a[c].id)}a[c].className=a[c].className.replace("purchrtb-dynamic","")}for(var f in b)window.tmntag.adunitClone(f,b[f],null,{disableRefreshRamp:!1})}}},window.tmntag.cmd.executeCommands=
function(){for(var a;a=window.tmntag.cmd.shift();)"function"==typeof a&&a()},window.tmntag.cmd.push=function(a){window.tmntag.cmd.executeCommands(),"function"==typeof a&&a()},window.tmntag.cmd.pushDefined=!0;C=function h(){window.tmntag.cmd.pushDefined?window.tmntag.cmd.executeCommands():setTimeout(h,100)};C(),window.tmntag.apiReady=!0,window.tmntag.timing.endHead=(new Date).getTime(),window.tmntag.timing.debug=function(a){var b={timing:{}};if(a&&window.tmntag.timing){a=window.tmntag.timing;b.timing.ramp=
{},b.timing.ramp.head=a.endHead-a.start,b.timing.ramp.loadTag=a.loadTag-a.start,b.timing.ramp.startTag=a.startTag-a.loadTag,b.timing.ramp.googleEnableServices=a.endEnableServices-a.startEnableServices,b.timing.ramp.endTag=a.endTag-a.startTag,b.timing.ramp.total=a.endTag-a.start}if(window.performance){a=window.performance.timing;b.timing.ttfb=a.responseStart-a.requestStart,b.timing.ttlb=a.responseEnd-a.responseStart,b.timing.ttsr=a.domInteractive-a.responseEnd}return b},window.tmntag.debug=function(){var a=
{};if(a.TMNAPI_VERSION=window.TMNAPI_VERSION,a.PREBID_TIMEOUT=window.PREBID_TIMEOUT,a.TMNTAG_VERSION=window.TMNTAG_VERSION,a.timing=window.tmntag.timing.debug(),a.googletag="undefined"!=typeof googletag?window.googletag:"none",a.initialLoadEnabled=window.tmntag_initialLoadDisabled,a.singleRequestEnabled=window.tmntag.sr,a.collapseEmptyDivs=window.tmntag.ced,a.tmntag=window.tmntag,a.tmntagCache=window.tmntagCache,a.tmntagDisplayed=window.tmntagDisplayed,a.adunits=window.tmntag.a,a.googleSlots=window.tmntag.slots,
a.pageLoation=window.tmntag_topLocation(),a.now=window.tmntag.t,a.timeZone=window.tmntag.tz,a.browserDim=window.tmntag.r,a.adParameters=window.tmntag.adparams,a.placement=window.tmntag.p,a.amazonAds="undefined"!=typeof amznads?window.amznads:"none",a.prebidSlots="undefined"!=typeof prebidSlots?window.prebidSlots:"none",a.prebidAds="undefined"!=typeof prebidAds?window.prebidAds:"none",a.target=void 0!==window.tmntag.pubtargets?window.tmntag.pubtargets:"none",a.adunitTarget=void 0!==window.tmntag.adtargets?
window.tmntag.adtargets:"none",a.adMarkups=void 0!==window.tmntag.markups?window.tmntag.markups:"none",window.googletag){var b=window.googletag.pubads().getSlots().map(function(a){a=a.getSlotElementId();return document.getElementById(a)?{Message:"Checked",DIV:a,Type:"GOOD"}:{Message:"Ad Slot declared in GPT, but NO DIV found on page",DIV:a,Type:"BAD !"}});console.table&&console.table(b),a.tagchecks=b}return a},window.tmntag.isMobile=e.h,window.tmntag_waitForCMP=m.e,window.tmntag.executeWithGDPRConsent=
m.a,window.userSyncPixels=new f.a,window.purch_history=function(a){a.pvLoggingDisabled=!0,a.pageHistory={},a.pageHistory[window.location.pathname]=1;!function(a){var b=a.replaceState;a.replaceState=function(c,d,e){return"function"==typeof a.onreplacestate&&window.location.pathname!==e&&a.onreplacestate(c,d,e),b.apply(a,arguments)};var c=a.pushState;a.pushState=function(b,d,e){return"function"==typeof a.onpushstate&&window.location.pathname!==e&&a.onpushstate(b,d,e),c.apply(a,arguments)}}(window.history),
history.onreplacestate=history.onpushstate=function(b,c,d){if(a.onPageChangedDisabled);else{{b=d;a.pageHistory[b]||(a.pageHistory[b]=1,window.purch_history_onNewPage(b))}}},window.purch_history_onNewPage=function(b){if(!a.pvLoggingDisabled){b={};a.pubtargets&&(b=Object(e.b)(a.pubtargets,["_ex","_rid"],b)),window.tmntag_triggerEvent("PV",{id:b._rid,e:b._ex,l:encodeURIComponent(window.tmntag_topLocation())})}}},window.purch_history(window.tmntag),window.tmntag.events=y.a,window.tmntag.inView=A.a,window.tmntag.autorefresh=
g.a,window.tmntag_processTmntagResponse=window.tmntag.processTmntagResponse=function(){if(window.TMNTAG_READY=1,void 0!==window.tmntag.pubtargets&&window.tmntag.pubtargets){window.experimentId&&window.tmntag.pubtargets.push(["_experiment",window.experimentId]);var a=R();0<a.indexOf("google")?window.tmntag.pubtargets.push(["_ts","gs"]):0<a.indexOf("yahoo")?window.tmntag.pubtargets.push(["_ts","ys"]):0<a.indexOf("bing")&&window.tmntag.pubtargets.push(["_ts","bs"])}window.tmntag.timing&&(window.tmntag.timing.startTag=
(new Date).getTime()),"undefined"!=typeof googletag&&window.googletag.cmd.push(function(){if(window.tmntag&&window.tmntag.isNonPersonalizedAds&&window.googletag.pubads().setRequestNonPersonalizedAds(1),"function"==typeof tmntag_defineSlot&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.a)if(window.tmntag&&1===window.tmntag.f){if(window.tmntag.adtargets)for(var a in window.tmntag.adtargets)window.tmntag.adtargets.hasOwnProperty(a)&&window.tmntag_defineAdUnit(a)}else for(a=0;a<window.tmntag.a.length;a++){var b=
window.tmntag.a[a].d;window.tmntag_defineAdUnit(b)}else window.tmntag_defineSlots();if("undefined"!=typeof tmntag&&void 0!==window.tmntag.pubtargets)for(a=0;a<window.tmntag.pubtargets.length;a++)window.googletag.pubads().setTargeting(window.tmntag.pubtargets[a][0],window.tmntag.pubtargets[a][1]);if(Object(z.b)()&&Object(z.c)(),"undefined"!=typeof tmntag&&void 0!==window.tmntag.su&&1===window.tmntag.su&&void 0!==window.tmntag.l&&window.googletag.pubads().set("page_url",decodeURIComponent(window.tmntag.l)),
1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.sr&&!0===window.tmntag.sr&&window.googletag.pubads().enableSingleRequest(),1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag_il&&!1===window.tmntag_il&&(console.log("- RAMP - DISABLE INITIAL LOAD"),window.googletag.pubads().disableInitialLoad()),1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.ced&&!0===window.tmntag.ced&&window.googletag.pubads().collapseEmptyDivs(),1!==window.tmntag.f){for(var c in window.tmntag.timing&&
(window.tmntag.timing.startEnableServices=(new Date).getTime()),"function"===window.tmntag.instartlogicEnabled&&window.tmntag.instartlogicEnabled()||window.googletag.enableServices(),D(),window.tmntag_callbacks.executeCallbacks(),window.tmntag.timing&&(window.tmntag.timing.endEnableServices=(new Date).getTime()),window.tmntag.slots)(a=document.getElementById(c))&&void 0!==a&&window.tmntagDisplayed&&1===window.tmntagDisplayed[c]&&window.googletag.display(c);"undefined"==typeof tmntag||void 0===window.tmntag_il||
!1!==window.tmntag_il||window.disable_refresh||(console.log("- RAMP - REFRESH"),window.googletag.pubads().refresh())}"function"==typeof window.tmntag_onAdTagReady&&window.tmntag_onAdTagReady()}),window.tmntag.timing&&(window.tmntag.timing.endTag=(new Date).getTime())}},function(f,g){f.exports=function(a){if(Array.isArray(a)){for(var b=0,d=new Array(a.length);b<a.length;b++)d[b]=a[b];return d}}},function(f,g){f.exports=function(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}},
function(f,g){f.exports=function(){throw new TypeError("Invalid attempt to spread non-iterable instance");}},function(f,g,a){f=function(a){function b(a,b,c,d){b=b&&b.prototype instanceof g?b:g;b=Object.create(b.prototype);d=new A(d||[]);return b._invoke=function(a,b,c){var d=N;return function(e,g){if(d===G)throw new Error("Generator is already running");if(d===O){if("throw"===e)throw g;return E()}for(c.method=e,c.arg=g;;){if(e=c.delegate)if(e=n(e,c)){if(e===B)continue;return e}if("next"===c.method)c.sent=
c._sent=c.arg;else if("throw"===c.method){if(d===N)throw d=O,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);d=G;e=f(a,b,c);if("normal"===e.type){if(d=c.done?O:u,e.arg===B)continue;return{value:e.arg,done:c.done}}"throw"===e.type&&(d=O,c.method="throw",c.arg=e.arg)}}}(a,c,d),b}function f(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(R){return{type:"throw",arg:R}}}function g(){}function m(){}function r(){}function l(a){["next","throw","return"].forEach(function(b){a[b]=
function(a){return this._invoke(b,a)}})}function p(a){var b;this._invoke=function(c,d){function e(){return new Promise(function(b,e){!function Q(b,c,d,e){b=f(a[b],a,c);if("throw"!==b.type){var g=b.arg;return(b=g.value)&&"object"==typeof b&&w.call(b,"__await")?Promise.resolve(b.__await).then(function(a){Q("next",a,d,e)},function(a){Q("throw",a,d,e)}):Promise.resolve(b).then(function(a){g.value=a,d(g)},function(a){return Q("throw",a,d,e)})}e(b.arg)}(c,d,b,e)})}return b=b?b.then(e,e):e()}}function n(a,
b){var c=a.iterator[b.method];if(c===z){if(b.delegate=null,"throw"===b.method){if(a.iterator.return&&(b.method="return",b.arg=z,n(a,b),"throw"===b.method))return B;b.method="throw",b.arg=new TypeError("The iterator does not provide a 'throw' method")}return B}c=f(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,b.delegate=null,B;return(c=c.arg)?c.done?(b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=z),b.delegate=null,B):c:(b.method=
"throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,B)}function c(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]),2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]),this.tryEntries.push(b)}function e(a){var b=a.completion||{};b.type="normal",delete b.arg,a.completion=b}function A(a){this.tryEntries=[{tryLoc:"root"}],a.forEach(c,this),this.reset(!0)}function y(a){if(a){var b=a[C];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1,b=function x(){for(;++c<
a.length;)if(w.call(a,c))return x.value=a[c],x.done=!1,x;return x.value=z,x.done=!0,x};return b.next=b}}return{next:E}}function E(){return{value:z,done:!0}}var z,M=Object.prototype,w=M.hasOwnProperty,F="function"==typeof Symbol?Symbol:{},C=F.iterator||"@@iterator",K=F.asyncIterator||"@@asyncIterator",H=F.toStringTag||"@@toStringTag";a.wrap=b;var N="suspendedStart",u="suspendedYield",G="executing",O="completed",B={},F={};F[C]=function(){return this};var I=Object.getPrototypeOf;(I=I&&I(I(y([]))))&&
I!==M&&w.call(I,C)&&(F=I);var J=r.prototype=g.prototype=Object.create(F);return m.prototype=J.constructor=r,r.constructor=m,r[H]=m.displayName="GeneratorFunction",a.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===m||"GeneratorFunction"===(a.displayName||a.name))},a.mark=function(a){return Object.setPrototypeOf?Object.setPrototypeOf(a,r):(a.__proto__=r,H in a||(a[H]="GeneratorFunction")),a.prototype=Object.create(J),a},a.awrap=function(a){return{__await:a}},l(p.prototype),
p.prototype[K]=function(){return this},a.AsyncIterator=p,a.async=function(c,d,e,f){var g=new p(b(c,d,e,f));return a.isGeneratorFunction(d)?g:g.next().then(function(a){return a.done?a.value:g.next()})},l(J),J[H]="Generator",J[C]=function(){return this},J.toString=function(){return"[object Generator]"},a.keys=function(a){var b=[],c;for(c in a)b.push(c);return b.reverse(),function x(){for(;b.length;){var c=b.pop();if(c in a)return x.value=c,x.done=!1,x}return x.done=!0,x}},a.values=y,A.prototype={constructor:A,
reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=z,this.done=!1,this.delegate=null,this.method="next",this.arg=z,this.tryEntries.forEach(e),!a)for(var b in this)"t"===b.charAt(0)&&w.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=z)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return f.type="throw",f.arg=a,c.next=b,d&&(c.method="next",c.arg=z),!!d}if(this.done)throw a;
for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],f=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var g=w.call(e,"catchLoc"),l=w.call(e,"finallyLoc");if(g&&l){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(g){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else{if(!l)throw new Error("try statement without catch or finally");if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,
b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&w.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};return c.type=a,c.arg=b,e?(this.method="next",this.next=e.finallyLoc,B):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,
this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),B},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),e(c),B}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;e(c)}return d}}throw new Error("illegal catch attempt");},delegateYield:function(a,b,c){return this.delegate=
{iterator:y(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=z),B}},a}(f.exports);try{regeneratorRuntime=f}catch(b){Function("r","regeneratorRuntime = r")(f)}},function(f,g){String.prototype.endsWith||(String.prototype.endsWith=function(a,b){return(void 0===b||b>this.length)&&(b=this.length),this.substring(b-a.length,b)===a}),String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return b=b||0,this.substr(b,a.length)===a}),Array.prototype.find||Object.defineProperty(Array.prototype,
"find",{value:function(a,b){if(null==this)throw new TypeError('"this" is null or not defined');var d=Object(this),f=d.length>>>0;if("function"!=typeof a)throw new TypeError("predicate must be a function");b=b;for(var g=0;g<f;){var m=d[g];if(a.call(b,m,g,d))return m;g++}}}),"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)}),"function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");
for(var d=Object(a),f=1;f<arguments.length;f++){var g=arguments[f];if(null!=g)for(var m in g)Object.prototype.hasOwnProperty.call(g,m)&&(d[m]=g[m])}return d},writable:!0,configurable:!0})}]));
tmntag.floorprices={};
tmntag.headerbidderstodrop={};try {
tmntag_ready(function() {

userSyncPixels._fragment=document.createElement("div");

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=185;userSyncPixels.create(11,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src="//bttrack.com/pixel/cookiesync?source=cfc80ad2-7c39-4243-92d6-3ecc1b9a38c6&secure=1";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=32;userSyncPixels.create("23_26_29_33",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var b=document.location.protocol==="https:"?"https":"http";a.src=b+"://ib.adnxs.com/getuid?"+b+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D23%2C26%2C29%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

function requestToken(){var a=document.getElementById(frameId);a.contentWindow.postMessage("GET_FB_TOKEN_198782813737","https://www.facebook.com")}function receiveFBToken(a){if(a.origin.indexOf("https://www.facebook.com")!==-1){var b="; expires="+a.data.expAfter;a=JSON.parse(a.data);document.cookie="up_28="+encodeURIComponent(a.fbToken)+b+"; path=/"}}
if(!window.gdprUser&&document.location.host.indexOf("creativebloq.com")<=0){var frameId="fb_iframe";if(typeof window.INSTART==="undefined"){try{var fbIframe=document.createElement("iframe");fbIframe.id=frameId;fbIframe.width="0";fbIframe.height="0";fbIframe.frameBorder="0";fbIframe.src="https://www.facebook.com/audiencenetwork/token/v1/";document.body.appendChild(fbIframe);fbIframe.onload=function(){requestToken()}}catch(a){console.error(a)}window.addEventListener("message",receiveFBToken,false)}};

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=undefined;
userSyncPixels.create("51_52_53_54",iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//sync.mathtag.com/sync/img?mt_exid=66&redir="+encodeURIComponent(d+"://pixel.servebom.com/partner?cb="+c+"&svc=us&id=51%2C52%2C53%2C54&uid=[MM_UUID]");b.appendChild(a);
userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=69;
userSyncPixels.create("22",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//us-u.openx.net/w/1.0/cm?id=de2d90e5-4d26-4c8c-a342-3edcde51fdb1&ph=25af9286-f23b-4b02-abcd-f2ee3b564dab&r="+d+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+c+"%26svc%3Dus%26id%3D22%26uid%3D";b.appendChild(a);
userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=104;
userSyncPixels.create(9,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){if(window.gdprUser)return;try{var c=document.createElement("script");c.src="//sync.go.sonobi.com/uc.js";userSyncPixels._fragment.appendChild(c)}catch(a){console.error(a)}try{var e=Math.floor(Math.random()*11E3),b=document.createElement("img"),d=document.location.protocol==="https:"?"https":"http";b.src=d+"://purch-sync.go.sonobi.com/us?"+d+"://pixel.servebom.com/partner?cb="+e+"&svc=us&id=9&uid=[UID]";userSyncPixels._fragment.appendChild(b);
return b}catch(a){console.error(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=13;userSyncPixels.create(24,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://ap.lijit.com/pixel?redir="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D24%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=28;userSyncPixels.create(14,iabId,"buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var a=document.createElement("iframe");a.style.display="none";a.src="//eb2.3lift.com/getuid?redir=%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D14%26uid%3D%24UID";b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;userSyncPixels.create(5,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.async=true;a.type="text/javascript";a.src="https://ads.pubmatic.com/AdServer/js/userSync.js";a.onload=function(){PubMaticSync.sync({pubId:46338,delay:1E3,url:"https://pixel.servebom.com/partner?svc=us&id=5&cb="+Math.floor(Math.random()*11E3)+"&uid=(PM_UID)",macro:"(PM_UID)"})};userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=24;userSyncPixels.create(36,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://purch-match.dotomi.com/match/bounce/current?networkId=20077&version=1&rurl="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D36%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;userSyncPixels.create(45,iabId,"creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.async=true;a.type="text/javascript";a.src="https://ads.pubmatic.com/AdServer/js/userSync.js";a.onload=function(){PubMaticSync.sync({pubId:155494,delay:1E3,url:"https://pixel.servebom.com/partner?svc=us&id=45&cb="+Math.floor(Math.random()*11E3)+"&uid=(PM_UID)",macro:"(PM_UID)"})};userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=202;
userSyncPixels.create(32,iabId,"space.com|tomsguide.com|tomshardware.com|livescience.com|laptopmag.com|newsarama.com|imore.com|androidcentral.com|windowscentral.com",true,function(){var c="pixel.servebom.com",a=Math.floor(Math.random()*11E3),f="tmx_sync_"+a,b="qds0l";if(b===""||b.indexOf("$")===0)return;var d=document.createElement("span");d.style.display="none";var e=document.location.protocol==="http:"?"http":"https",b=b+".publishers.tremorhub.com",c=e+"://"+b+"/pubsync?redir="+e+":%2F%2F"+c+"%2Fpartner%3Fcb%3D"+a+"%26svc%3Dus%26id%3D32%26uid%3D%5Btvid%5D",a=document.createElement("iframe");a.id=
a.name=f;a.src=c;a.frameBorder=0;a.frameSpacing=0;a.scrolling="no";a.width=1;a.height=1;d.appendChild(a);userSyncPixels._fragment.appendChild(d);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=81;
userSyncPixels.create(17,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=document.location.protocol==="https:"?"https":"http",b=document.createElement("span"),d=Math.floor(Math.random()*11E3);b.style.display="none";var a=document.createElement("iframe");a.style.display="none";a.src=c+"://bh.contextweb.com/bh/rtset?pid=558527&cb="+d+"&ev=1&rurl="+c+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D17%26cb%3D"+d+"%26uid%3D%25%25VGUID%25%25";b.appendChild(a);userSyncPixels._fragment.appendChild(b);
return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=10;
userSyncPixels.create(2,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol;a.defer=true;var d="ssum.casalemedia.com";if(document.location.protocol==="https:")d="ssum-sec.casalemedia.com";a.src=c+"//"+d+"/usermatch?r="+b+"&s=181869&cb="+c+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+b+"%26svc%3Dus%26id%3D2%26uid%3D";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=335;userSyncPixels.create(42,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=1&gc="+b.metadata+"&gce=1";userSyncPixels._fragment.appendChild(a)});else{a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=0&gc=&gce=1";userSyncPixels._fragment.appendChild(a)}return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=undefined;userSyncPixels.create(15,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol;a.async=true;a.src=b+"//sync.adkernel.com/user-sync?zone=39660&r="+b+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D15%26uid%3D{UID}";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;
userSyncPixels.create(46,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//ads.pubmatic.com/AdServer/js/user_sync.html?r="+c+"&p=156007&predirect="+d+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+c+"%26svc%3Dus%26id%3D46%26uid%3D";b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=27,iabId=236;userSyncPixels.create(partnerId,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://px.powerlinks.com/user/identify?rurl=https%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D"+partnerId+"%26uid%3D${USER}";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=52;userSyncPixels.create("19",iabId,"",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("iframe");a.style.display="none";a.async=true;var b="assets.rubiconproject.com";if(document.location.protocol==="https:")b="secure-assets.rubiconproject.com";var d="11868",e="us-east";a.src=document.location.protocol+"//"+b+"/utils/xapi/multi-sync.html?r="+c+"&p="+d+"&endpoint="+e;userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=55,iabId=184;userSyncPixels.create(partnerId,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://cookie-matching.mediarithmics.com/v1/get_user_agent_id?dom_token=purch18";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=57,iabId=25;
userSyncPixels.create(partnerId,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=1&gdpr_consent="+b.metadata+"&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)});else{a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=0&gdpr_consent=&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=183;userSyncPixels.create("25",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var b=document.location.protocol==="https:"?"https":"http";a.src=b+"://cs.emxdgt.com/um?redirect="+b+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D25%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=36;userSyncPixels.create("58",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var c=document.location.protocol==="https:"?"https":"http";a.src=c+"://sync.1rx.io/usersync2/rmpssp?sub=purch&redir=https%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+b+"%26svc%3Dus%26id%3D58%26uid%3D%5BRX_UUID%5D";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=58;
userSyncPixels.create("59",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//pixel.33across.com/ps?m=xch&rt=html&id=0013300001kQj3GAAS&ru="+encodeURIComponent(d+"://pixel.servebom.com/partner?cb="+c+"&svc=us&id=59&uid=33XUSERID33X");b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

(function(){document.body.appendChild(userSyncPixels._fragment)})();

});
} catch (e) {
console.error(e);
}
